Dart-Code/Dart-Code

- src/dart_hover_provider.ts
- display the element summary (followed by the dartdoc)
- limit the total length to ~20 markdown lines (until the tooltip UI supports scrolling)
- show the element summary in dart code style
> Display element summary followed by the dartdoc in Hovers

- package.json
- src/analyzer.ts
- src/dart_diagnostic_provider.ts
- src/extension.ts
- filter todos from the problems view (and add a preferences for it)
- add a hidden flag to start the analysis server diagnostic server up on a specified port
> filter todos from the problems view

- src/dart_reference_provider.ts
- src/extension.ts
> Implement ReferenceProvider for Find References

- package.json
- src/editors.ts
- src/extension.ts
- src/providers/dart_commands.ts
- implement organize directives
- fix https://github.com/Dart-Code/Dart-Code/issues/78
> implement organize directives

- appveyor.yml
> Enabled tests on AppVeyor.

- src/providers/dart_workspace_symbol_provider.ts
- work towards https://github.com/Dart-Code/Dart-Code/issues/62
- tweak the workspace symbols display
The results are for running in the VSCode Insiders (nightly) build. This uses `package:foo/bar.dart` for package libraries, uses relative paths for other libraries, and displays the container hierarchy in the name for elements (`Foo.bar` for class members; `foo` for top-level symbols).
> tweak the workspace symbols display

- src/providers/dart_document_symbol_provider.ts
> Tweaks to display in document symbol provider.

- package.json
- src/debug/debug_impl.ts
- src/debug/debug_protocol.ts
- src/debug/utils.ts
A fairly complete implementation of a debugger:
- breakpoints
- stepping
- async stepping
- breaking at exceptions
- support multiple isolates
- exp. evaluation on hover
- watchpoint expressions
- repl exp. eval
This may need to be iterated on a bit. I'm having some trouble with an import of a JS `ws` packages. Probably best to land this after a major release? I can also push a PR to a branch on the Dart-Code repo, so we can iterate more easily there.
@DanTup
> Debugger implementation

- src/providers/dart_completion_item_provider.ts
> Add method/function/constructor parameter information for completion items

- package.json
- snippets/dart.json
> Implement Snippets

- src/debug/debug_impl.ts
- src/debug/debug_protocol.ts
- add a `shouldLogTraffic` flag to log debugger traffic
> add debugger logging

- .gitignore
> add two files to .gitignore

- src/debug/debug_impl.ts
- redux of https://github.com/Dart-Code/Dart-Code/pull/126; improve the display of variables
> debugger variable display

- src/commands/channels.ts
- src/extension.ts
- src/providers/dart_rename_provider.ts
- src/utils.ts
For issue #31
Feel free to comment on code structure/performance/etc.
> Implement RenameProvider

- .gitignore
- src/analytics.ts
- src/analyzer_status_reporter.ts
- src/config.ts
- src/editors.ts
- src/file_change_handler.ts
- src/open_file_tracker.ts
- src/providers/dart_diagnostic_provider.ts
- src/providers/dart_workspace_symbol_provider.ts
- run the formatter over the  source files
- tweak the .gitignore file
> run the formatter over source files

- .vscode/settings.json
- src/editors.ts
Follow up from https://github.com/Dart-Code/Dart-Code/pull/154, set detect indentation to false.
> set detect indentation to false

- src/providers/dart_hover_provider.ts
Improve the display of dartdoc hovers (esp. for the VSCode insiders release):
(this still works well with the current stable version of vscode)
@DanTup
> improve the dartdoc display

- src/debug/debug_impl.ts
- src/debug/debug_protocol.ts
Support paged Lists in the debugger:
@DanTup 
(and, rename a class in the debugger protocol wrapper to be the same as the spec name; `VMObjRef` ==> `VMObjectRef`)
> support paged lists

- package.json
Update to the latest vscode APIs.
> update to the latest vscode libs

- package.json
- src/commands/channels.ts
- src/debug/debug_impl.ts
- src/utils.ts
- tsconfig.json
- typings/node.d.ts
- typings/vscode-typings.d.ts
- upgrade some deps as specified in the 1.6 release notes
- fix a few new typescript warnings
- fix https://github.com/Dart-Code/Dart-Code/issues/207
> upgrade deps to typescript 2

- src/analysis/analyzer.ts
- src/config.ts
- add support for `--instrumentation-log-file`
- add support for additional, arbitrary args to the analysis server
@DanTup
> add some additional analysis server args

- package.json
- src/user_config_prompts.ts
> Update to TypeScript 2.1.5

- package.json
- src/analysis/analyzer.ts
- src/analysis/analyzer_gen.ts
- src/analyzer_status_reporter.ts
- src/commands/type_hierarchy.ts
- src/debug/debug_impl.ts
- src/debug/debug_protocol.ts
- src/debug/utils.ts
- src/providers/dart_code_action_provider.ts
- src/providers/dart_rename_provider.ts
- src/user_config_prompts.ts
- tsconfig.json
⚠️ I am expecting changes will need to be made. Please review the approach I used in each situation carefully to determine if it's what you really want to go with.
Related to #187
> Set noImplicitAny to true and fix all errors

- package.json
- src/commands/sdk.ts
- src/extension.ts
- src/utils.ts
Fixes #287.
Separated the PRs because this one has a lot more changes by itself.
> Flutter packages commands + wiring

- snippets/dart.json
Added snippets for test and group. I find myself using these snippets a lot.
> Add snippets for test and group

- package.json
- src/config.ts
- src/providers/dart_diagnostic_provider.ts
Fixes #359 
I added `"HINT"` as well, as they seem to be in the same class of ignorable notices.
> Added lint/hint name display

- src/commands/sdk.ts
Fixes #472
Not my prettiest work, but it tested well.
I was going to use
`if (sdks.projectType in [ProjectType.Flutter, ProjectType.Fuchsia])`
but that pegged my processor, so I gave up on that idea. 😕
As for why there are 3 commits, I honestly don't know what git is doing anymore.
> Re-enable `flutter packages get` on pubspec save.

- test/dart_only/providers/snippet_provider.test.ts
- test/flutter_only/providers/snippet_provider.test.ts
- test/helpers.ts
Sending PR to test CodeClimate's measuring of coverage on PRs.
> Add some basic snippet tests

- package.json
> Add keybind for Organize Directives

- package.json
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/providers/debug_config_provider.ts
> Add support for flutter profile/release mode

- .vscode/settings.json
- package-lock.json
- package.json
- src/commands/edit.ts
- src/commands/refactor.ts
- src/extension.ts
- src/project.ts
- src/providers/dart_rename_provider.ts
- src/providers/refactor_code_action_provider.ts
- src/utils.ts
- test/dart_only/commands/organize_directives.test.ts
- test/dart_only/commands/sort_members.test.ts
- test/dart_only/providers/dart_document_symbol_provider.test.ts
- test/dart_only/providers/dart_hover_provider.test.ts
- test/dart_only/providers/dart_rename_provider.test.ts
- test/dart_only/providers/dart_type_formatting_edit_provider.test.ts
- test/dart_only/providers/dart_workspace_symbol_provider.test.ts
- test/dart_only/refactors/extract_method.test.ts
- test/flutter_only/providers/dart_document_symbol_provider.test.ts
- test/flutter_only/providers/fix_code_action_provider.test.ts
- test/helpers.ts
- test/multi_root_upgraded/extension.test.ts
- test/not_activated/flutter_create/extension.test.ts
- tslint.json
> Implement EXTRACT_METHOD refactor

- package.json
- src/analysis/open_file_tracker.ts
- src/commands/go_to_super.ts
- src/commands/type_hierarchy.ts
- src/extension.ts
- test/dart_only/commands/go_to_super_method.test.ts
- test/dart_only/commands/organize_directives.test.ts
- test/dart_only/outline_tracking.test.ts
- test/helpers.ts
- test/multi_root_upgraded/extension.test.ts
- test/test_projects/hello_world/lib/go_to_super_method/derived.dart
- test/test_projects/hello_world/lib/go_to_super_method/super.dart
Fixes #505.
There are some test failures that aren't directly related (they're in the outline tracking code that was added to support this) that should be fixed before merging.
> Implement Go to super method

- package.json
- src/commands/debug.ts
- src/commands/sdk.ts
Requires Code v1.22 so can't merge till after that ships.
> Allow long running tasks to be cancelled

- test/dart_only/debug/dart_cli.test.ts
- test/flutter_only/debug/flutter_test.test.ts
There are still some skips, but mostly they're working now and consistent across all platforms.
> Fix debugger tests

- src/commands/refactor.ts
- src/providers/refactor_code_action_provider.ts
- test/dart_only/refactors/extract_method.test.ts
- test/flutter_only/refactors/extract_widget.test.ts
- test/helpers.ts
> Add support for Flutter EXTRACT_WIDGET refactor

- .travis.yml
- appveyor.yml
- src/analysis/analyzer.ts
- src/analysis/analyzer_gen.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test.ts
- src/extension.ts
- src/flutter/flutter_daemon.ts
- src/services/stdio_service.ts
- test/test_all.ts
> Improve per-test log files and ensure always uploaded

- src/analysis/file_change_handler.ts
> Remove multi-cursor workaround (Requires Code v1.23)

- src/debug/dart_debug_impl.ts
- test/dart_only/debug/dart_cli.test.ts
> Implement conditional breakpoints

- src/debug/dart_debug_impl.ts
- test/dart_only/debug/dart_cli.test.ts
> Implement logpoints

- .travis.yml
- .vscode/launch.json
- appveyor.yml
- src/analysis/analyzer.ts
- src/commands/sdk.ts
- src/extension.ts
- test/flutter_repository/extension.test.ts
- test/flutter_repository/index.ts
- test/helpers.ts
- test/test_all.ts
Tests that extension activates, packages restore, analysis completes and there are 0 reported errors.
> Add tests to ensure Flutter Repo opens with 0 reported errors

- src/debug/dart_debug_impl.ts
> Add an index to map entries for debugger display

- src/debug/dart_debug_impl.ts
> Delay sending setLibraryDebuggables until isolate is runnable

- package.json
- src/flutter/device_manager.ts
- src/flutter/flutter_daemon.ts
- src/providers/debug_config_provider.ts
Fixes #490.
I'm tagging this as v2.13 but whether it's merged may depend on the progress of https://github.com/flutter/flutter/pull/17466 (don't want to announce something people can't use).
> Add support for launch emulators

- test/test_all.ts
Killing the node process doesn't kill Code, so just bring down the whole run (hopefully we'll get to the bottom of what's hanging when this occurs!).
> When terminating tests, abort whole run

- package.json
- src/analysis/analyzer.ts
- src/commands/edit.ts
- test/dart_only/commands/complete_statement.test.ts
- test/helpers.ts
Fixes #665.
We should get confirmation that we're understanding the offsets correctly ([see here](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/BrVNADpvx-o)) before merging, and depending on the response to https://github.com/dart-lang/sdk/issues/33034 we might need to make this conditional.
> Implement complete statement

- package.json
- src/config.ts
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- test/dart_only/debug/dart_cli.test.ts
- test/debug_helpers.ts
- test/helpers.ts
- test/test_projects/hello_world/bin/getters.dart
Fixes #401.
@devoncarew Could you have a scan over this to see if it all makes sense? There's a TODO about a few things I'm not totally happy with, but it does seem to work. I don't know what the perf impact would be like on a big object, but someone told me the VM is fast :)
> Show getters in debugger watch/variables/hovers

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/flutter/flutter_daemon.ts
- src/flutter/flutter_types.ts
- src/services/stdio_service.ts
- test/flutter_only/debug/flutter_run.test.ts
> Terminate flutter run better when clicking Stop during a build

- src/services/stdio_service.ts
> Ensure stdio subscriptions are removed during dispose

- src/commands/logging.ts
- src/utils/log.ts
> Allow user to select which categories to log

- src/debug/flutter_debug_impl.ts
Fixes #941.
Tested manually on Windows and Mac - all breakpoints come through with host paths, nothing has the `baseUri` in it.
> Remove baseUri mapping for Flutter

- src/flutter/device_manager.ts
- src/flutter/flutter_daemon.ts
> Add an option for creating an emulator if the daemon supports it

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
This was already coming from the test framework; we just weren't getting it back to the user.
> Show "finishing current test" output in debug console when terminating tests

- src/commands/edit.ts
- src/editors.ts
- src/providers/source_code_action_provider.ts
> Don't use the active editor for source actions

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test.ts
- src/debug/flutter_test_debug_impl.ts
- src/debug/test_runner.ts
- src/debug/utils.ts
> Allow passing environment variables through

- src/utils.ts
> Don't assume all test folders are tests

- package.json
- src/commands/debug.ts
- src/extension.ts
- src/providers/debug_config_provider.ts
> Add a command to re-run the last thing config that ran

- src/commands/sdk.ts
> Show cancellation button on long running commands

- package.json
- src/commands/logging.ts
- src/extension.ts
> Use the VS Code-provided log folder

- src/extension.ts
This reverts commit 120155449257cea4705151fcad9fed2eadc05b20.
Fixes #1164.
> Revert "Revert "Exclude PUB_CACHE and APPDATA folders by default on Windows""

- src/debug/dart_debug_impl.ts
Fixes #1117.
@devoncarew Does this seem reasonable? The issue is that if a user sets breaking on "All Exceptions" they start hitting exceptions in the `pub` isolate code, for example:
This seems undesirable since it's unrelated to user code (which runs in its own isolate). Note this change does not stop it from breaking on caught exceptions in framework code that runs in the users isolates, it's purely infrastructure code that I think they essentially consider a bug-free black box.
> Don't break in pub when using "All Exceptions" pause mode

- package.json
- src/config.ts
- src/extension.ts
- src/providers/dart_diagnostic_provider.ts
- src/providers/ignore_lint_code_action_provider.ts
> Add the ability to add "// ignore: xxx" quick-fixes

- src/providers/debug_config_provider.ts
- src/utils.ts
- test/flutter_only/debug/flutter_run.test.ts
> Include cwd when guessing entry points

- syntaxes/dart.json
> Improve syntax highlighting to understand code blocks in dartdocs

- package-lock.json
- package.json
- src/analysis/analyzer.ts
- src/code_lens/test_code_lens_provider.ts
- src/commands/logging.ts
- src/dartdocs.ts
- src/debug/dart_debug_impl.ts
- src/debug/utils.ts
- src/decorations/hot_reload_coverage_decorations.ts
- src/providers/dart_implementation_provider.ts
- src/providers/dart_reference_provider.ts
- src/providers/dart_workspace_symbol_provider.ts
- src/sdk/utils.ts
- src/utils/log.ts
- src/utils/test.ts
- src/views/test_view.ts
- test/dart_only/providers/dart_document_symbol_provider.test.ts
- test/helpers.ts
Fixes #1287. We only used a few functions so it seemed overkill to pull in a 1.5MB library.
> Remove lodash

- src/extension.ts
- src/providers/dart_completion_item_provider.ts
> Remove space as a trigger character

- src/commands/sdk.ts
- src/utils.ts
This only walks down one level but should be better than just showing top levels. Fixes #1272.
> Switch workspace folder picker to custom list of projects

- src/commands/debug.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/flutter/flutter_types.ts
- src/utils/debug.ts
> Show a progress notification for whole build, not just some parts

- package.json
- src/commands/debug.ts
- src/config.ts
- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/providers/debug_config_provider.ts
> Add an option for changing Restart button to Hot Restart

- src/debug/dart_debug_impl.ts
- src/flutter/capabilities.ts
- test/dart_only/debug/dart_cli.test.ts
- test/helpers.ts
- test/test_projects/hello_world/bin/local_library.dart
- test/test_projects/hello_world/pubspec.yaml
- test/test_projects/my_library/lib/my_thing.dart
- test/test_projects/my_library/pubspec.yaml
> Dont consider local packages external

- src/commands/debug.ts
- src/constants.ts
- src/context.ts
- src/extension.ts
- src/user_prompts.ts
- test/dart_only/user_prompts.test.ts
- test/helpers.ts
@devoncarew @jacob314 WDYT about this to help people find DevTools? It'll only appear once per 20 hours, and only up to 10 times maximum (and obvious, never again if you click Don't Show Again).
Fixes #1503.
> Add a notification about DevTools

- src/commands/sdk.ts
- src/flutter/capabilities.ts
- src/sdk/flutter_docs_snippets.ts
> Read snippets from Flutter if supported (to reduce mismatched versions between master/stable)

- package.json
- src/analysis/analysis_server_types.ts
- src/analysis/analyzer.ts
- src/analysis/analyzer_gen.ts
- src/analysis/analyzer_status_reporter.ts
- src/analysis/open_file_tracker.ts
- src/config.ts
- src/extension.ts
- src/providers/dart_completion_item_provider.ts
- test/dart_only/providers/completion_item_provider.test.ts
- test/dart_only/providers/dart_document_symbol_provider.test.ts
- test/helpers.ts
- test/test_projects/hello_world/.vscode/settings.json
- test/test_projects/hello_world/lib/enum.dart
- test/test_projects/hello_world/lib/everything.dart
> Include unimported items in completions, and insert import statements when selecting them

- .travis.yml
- appveyor.yml
- src/debug/dart_debug_impl.ts
- src/sdk/dev_tools.ts
- src/utils/vscode/debug.ts
> Use URIs for VM Service connections instead of ports

- package.json
- src/config.ts
- src/utils/misc.ts
> Improve typing of config class and support null where appropriate for the settings UI

- package.json
- src/commands/debug.ts
- src/flutter/vm_service_extensions.ts
> Add toggle for Check Elevations

- package.json
- src/config.ts
- src/extension.ts
- src/flutter/flutter_daemon.ts
> Add an option to ADB Connect at startup on ChromeOS 

- src/commands/sdk.ts
Previously we could simultaneously fire off many, but pub doesn't handle concurrent fetches very well. This will run it automatically for one change, but show the "Some packages are out of date" prompt for > 1.
Fixes #1651.
> When multiple pubspecs change at once, prompt to fetch packages

- src/commands/debug.ts
- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/flutter/vm_service_extensions.ts
> Tweaks to setPubRootDirectories

- src/commands/sdk.ts
- src/user_prompts.ts
> Ensure pubspec.yaml watcher doesn't trigger during Stagehand/Flutter create

- .travis.yml
- appveyor.yml
- package.json
- src/analysis/file_change_handler.ts
- src/commands/debug.ts
- src/config.ts
- src/constants.ts
- src/debug/dart_debug_impl.ts
- src/flutter/vm_service_extensions.ts
- src/sdk/dev_tools.ts
- test/dart_debug_client.ts
- test/dart_only/debug/dart_cli.test.ts
- test/flutter_only/debug/flutter_run.test.ts
- test/flutter_web_only/debug/flutter_web.test.ts
Requires these fixes released before we can merge:
Fixes #1505.
> Let DevTools handle launching the browser so we always get Chrome

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_test_debug_impl.ts
- src/debug/flutter_web_debug_impl.ts
- test/dart_only/debug/dart_test.test.ts
- test/flutter_create_tests/flutter_create.test.ts
- test/flutter_only/debug/flutter_run.test.ts
- test/flutter_only/debug/flutter_run_attach.test.ts
- test/flutter_only/debug/flutter_test.test.ts
- test/flutter_web_only/debug/flutter_web.test.ts
- test/flutter_web_only/debug/flutter_web_test.test.ts
- test/helpers.ts
- test/test_projects/flutter_hello_world/test/another_test.dart
- test/test_projects/flutter_hello_world/test/broken_test.dart
- test/test_projects/flutter_hello_world/test/other_test.dart
- test/test_projects/flutter_hello_world/test/widget_test.dart
- test/test_runner.ts
> Only connect the VM in noDebug mode for Flutter run

- src/constants.ts
- src/context.ts
- src/user_prompts.ts
- test/dart_only/user_prompts.test.ts
- test/helpers.ts
> Add a link to the Flutter Q2 survey

- package.json
- src/analysis/analyzer.ts
- src/analysis/open_file_tracker.ts
- src/config.ts
- src/decorations/flutter_ui_guides_decorations.ts
- src/decorations/test_line_decorations.ts
- src/extension.ts
This adds a somewhat-functional preview of Flutter UI Guides. VS Code doesn't have a nice API for this sort of thing so it has many quirks I haven't yet found a good fix for. I've opened https://github.com/microsoft/vscode/issues/73780 to try and start a discussion for better support for features like this in VS Code.
> Add UI guides preview

- src/analysis/utils.ts
- src/commands/sdk.ts
- src/extension.ts
- src/project.ts
- src/pub/pub.ts
- src/views/packages_view.ts
> Add getWorkspaceProjectFolders to catch nested projects in more places

- package.json
- src/commands/debug.ts
- src/providers/debug_config_provider.ts
> Add a new Flutter: Attach to Process option that prompts for VM Service

- package-lock.json
- package.json
- src/extension/extension.ts
- src/shared/utils/fs.ts
Also allows us to move glob to devDependencies.
> Switch to fs.realpathSync.native instead of custom code

- src/test/test_projects/flutter_hello_world/example/lib/main.dart
- src/test/test_projects/flutter_hello_world/lib/broken.dart
- src/test/test_projects/flutter_hello_world/lib/main.dart
- src/test/test_projects/flutter_web/broken/lib/main.dart
- src/test/test_projects/hello_world/bin/broken.dart
- src/test/test_projects/hello_world/bin/getters.dart
- src/test/test_projects/hello_world/bin/main.dart
- src/test/test_projects/hello_world/lib/completion.dart
- src/test/test_projects/hello_world/lib/create_method/class_b.dart
- src/test/test_projects/hello_world/lib/everything.dart
- src/test/test_projects/hello_world/lib/go_to_implementation.dart
After Dart 2.0, `new` keyword did not needed.
I remove all `new ` keyword on Dart-Code
> Remove new keyword on Dart 2.0 >

- src/extension/user_prompts.ts
- src/shared/constants.ts
- src/shared/vscode/user_prompts.ts
- src/shared/vscode/workspace.ts
- src/test/dart_only/user_prompts.test.ts
- src/test/helpers.ts
> Add prompt for Flutter 2019 Q3 survey

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/shared/flutter/structured_errors.ts
- src/shared/utils/colors.ts
- src/test/dart_debug_client.ts
- src/test/flutter_only/debug/flutter_run.test.ts
@devoncarew I think these match your latest changes?
> Improve error display

- package.json
- src/extension/commands/sdk.ts
- src/extension/config.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/providers/debug_config_provider.ts
> Add support for passing additional args to all Flutter processes

- src/extension/commands/analyzer.ts
- src/extension/commands/debug.ts
- src/extension/extension.ts
- src/extension/pub/global.ts
- src/extension/sdk/dev_tools.ts
- src/extension/sdk/update_check.ts
- src/extension/sdk/utils.ts
- src/extension/user_prompts.ts
- src/extension/utils/vscode/editor.ts
- src/shared/vscode/interfaces.ts
- src/shared/vscode/user_prompts.ts
- src/shared/vscode/utils.ts
- src/test/dart_only/debug/dart_cli.test.ts
- src/test/dart_only/user_prompts.test.ts
- src/test/flutter_only/debug/flutter_run.test.ts
- src/test/flutter_web_only/debug/flutter_web.test.ts
> Switch to using env.openExternal to get automatic port forwarding

- src/extension/providers/debug_config_provider.ts
- src/shared/vscode/device_manager.ts
- src/test/flutter_only/device_manager.test.ts
> Use emulator names in picker for running devices

- .github/workflows/build-and-test.yml
Currently only enabled for a test branch (that doesn't exist).
> Add script for running GitHub actions

- src/extension/analysis/analyzer_gen.ts
- src/extension/code_lens/test_code_lens_provider.ts
- src/extension/commands/go_to_super.ts
- src/extension/commands/type_hierarchy.ts
- src/extension/decorations/flutter_icon_decorations.ts
- src/extension/extension.ts
- src/extension/providers/dart_completion_item_provider.ts
- src/extension/providers/dart_diagnostic_provider.ts
- src/extension/providers/dart_document_symbol_provider.ts
- src/extension/providers/dart_implementation_provider.ts
- src/extension/providers/dart_reference_provider.ts
- src/extension/providers/dart_rename_provider.ts
- src/extension/providers/dart_workspace_symbol_provider.ts
- src/extension/providers/legacy_dart_workspace_symbol_provider.ts
- src/extension/utils.ts
- src/shared/analysis_server_types.ts
- src/shared/interfaces.ts
- src/shared/utils/dartdocs.ts
- src/shared/utils/flutter_outline.ts
- src/shared/vscode/icon_range_computer.ts
- src/shared/vscode/utils.ts
- src/test/flutter_only/decorations/flutter_icons.test.ts
- src/test/helpers.ts
> Show Flutter icons in the gutter

- src/extension/utils/processes.ts
- src/shared/utils/outline.ts
- src/test/dart_only/debug/dart_test.test.ts
- src/test/test_projects/hello_world/test/tree_test.dart
Fixes #2053, but escaping may need tweaking on Windows (AppVeyor should catch that).
> Fix quoted tests

- package.json
- src/extension/commands/test.ts
- src/extension/extension.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_only/commands/go_to_test_or_implementation.test.ts
- src/test/dart_only/commands/run_test_at_cursor.test.ts
- src/test/flutter_only/commands/run_test_at_cursor.test.ts
- src/test/helpers.ts
- src/test/test_projects/hello_world/lib/basic.dart
> Add "Go to Test/Implementation File" command

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/threads.ts
- src/extension/commands/test.ts
- src/extension/config.ts
- src/extension/decorations/closing_labels_decorations.ts
- src/extension/providers/dart_implementation_provider.ts
- src/extension/providers/dart_workspace_symbol_provider.ts
- tsconfig.json
This leaves just one issue, which is because of weird typing in VS Code where we have to pass an undefined to a type that says it doesn't accept it (related to https://github.com/microsoft/vscode/issues/51695).
> TypeScript strictNullChecks changes

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/threads.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/flutter/flutter_outline_view.ts
- src/extension/providers/dart_diagnostic_provider.ts
- src/extension/providers/dart_workspace_symbol_provider.ts
- src/extension/views/test_view.ts
- src/shared/utils.ts
- tsconfig.json
Needs rebasing over https://github.com/Dart-Code/Dart-Code/pull/2065 once it lands, as this contains that too.
> TypeScript strictPropertyInitialization changes

- package.json
- src/extension/analysis/analyzer.ts
- src/extension/analysis/analyzer_das.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/sdk/capabilities.ts
> Add a tickbox to enable completion model

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/utils.ts
- src/extension/config.ts
- src/extension/providers/debug_config_provider.ts
> Support debugger Rewind behind a preview flag

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/utils.ts
- src/extension/commands/debug.ts
- src/extension/utils/vscode/debug.ts
- src/test/dart_debug_client.ts
- src/test/dart_only/debug/dart_cli.test.ts
> Support running in pseudo terminal to support stdin

- package.json
- src/extension/config.ts
- src/extension/providers/dart_completion_item_provider.ts
Currently behind a flag (`dart.previewNewCompletionPlaceholders`).
> Support inserting placeholders for @required arguments

- src/extension/user_prompts.ts
> Show a message if the user has installed Flutter in a protected folder

- src/extension/extension.ts
- src/extension/flutter/flutter_outline_view.ts
> Fix updating of Flutter Outline for files outside works[aces

- src/debug/dart_debug_protocol.ts
> Delay processing of events in the debugger to match request responses

- package-lock.json
- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/extension/analysis/file_tracker_das.ts
- src/extension/commands/debug.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/capabilities.ts
- src/extension/utils/vscode/debug.ts
- src/test/dart/providers/completion_item_provider.test.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug_client.ts
Fixes #2148 and will help towards #2230.
> Use --write-service-info for extracting VM service URI

- package-lock.json
- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/extension/analysis/file_tracker_das.ts
- src/extension/commands/debug.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/capabilities.ts
- src/extension/utils/vscode/debug.ts
- src/test/dart/providers/completion_item_provider.test.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug_client.ts
(Re-merge of https://github.com/Dart-Code/Dart-Code/pull/2304 because GitHub errorred during the merge)
Fixes #2148 and will help towards #2230.
> Use --write-service-info for extracting VM service URI to better support Terminal mode

- package-lock.json
- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/test_runner.ts
- src/debug/utils.ts
- src/debug/web_debug_impl.ts
- src/debug/web_run.ts
- src/extension/analysis/analyzer_das.ts
- src/extension/commands/debug.ts
- src/extension/commands/sdk.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/pub/build_runner_task_provider.ts
- src/extension/sdk/dev_tools.ts
- src/extension/utils/processes.ts
- src/extension/utils/vscode/debug.ts
- src/shared/processes.ts
- src/shared/services/stdio_service.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug_client.ts
- src/test/debug_client_ms.ts
> Use runInTerminalRequest for spawning CLI apps in client terminal

- src/extension/extension.ts
- src/extension/user_prompts.ts
- src/shared/constants.ts
- src/shared/fetch.ts
- src/shared/interfaces.ts
- src/shared/pub/api.ts
- src/shared/vscode/interfaces.ts
- src/shared/vscode/user_prompts.ts
- src/shared/vscode/workspace.ts
- src/test/dart/user_prompts.test.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/flutter_debug/debug/flutter_run.test.ts
- src/test/helpers.ts
- src/test/web_debug/debug/web.test.ts
Equiv of https://github.com/flutter/flutter-intellij/pull/4449.
@jayoung-lee @pq FYI! I have tested it with my own copy of the JSON file with varying dates (plus updated the automated tests) but please let me know when you have dates for the next survey and update the file, so I can double-check it. Thanks!
> Switch to reading Flutter survey data from the web

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/run_daemon_base.ts
- src/debug/utils.ts
- src/debug/web_debug_impl.ts
- src/debug/web_run.ts
- src/extension/commands/debug.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/capabilities/flutter.ts
- src/shared/services/stdio_service.ts
- src/test/dart_debug_client.ts
> Expose debug services and force WebSockets for VM proxy to support remote/container debugging

- package.json
- src/extension/commands/debug.ts
- src/extension/extension.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/constants.ts
> Implement re-run last test session

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/extension/commands/debug.ts
> Wait for main process PIDs when terminating

- src/extension/commands/sdk.ts
- src/extension/utils.ts
- src/shared/utils/fs.ts
> Change more project scanning to be async to reduce chance of triggering "high CPU" warning

- src/extension/sdk/dev_tools.ts
- src/shared/constants.ts
> Prompt to reactivate DevTools if it fails to start

- src/extension/decorations/closing_labels_decorations.ts
- src/extension/lsp/closing_labels_decorations.ts
- src/extension/pub/global.ts
- src/shared/utils.ts
- src/test/dart/util.test.ts
Fixes #2436.
@jacob314 FYI if you'd like to review the logic here (I can't easily use `pub_semver` because this is TS/JS).
> Handle pub package versions the same way as pub

- package.json
- src/extension/code_lens/main_code_lens_provider.ts
- src/extension/code_lens/test_code_lens_provider.ts
- src/extension/code_lens/test_code_lens_provider_lsp.ts
- src/shared/vscode/debugger.ts
- src/test/dart/providers/main_code_lens_provider.test.ts
- src/test/dart/providers/test_code_lens_provider.test.ts
> Support multiple templates in launch configs

- src/extension/commands/debug.ts
- src/shared/vscode/workspace.ts
> Prompt to change debug settings if breakpoints outside workspace

- package.json
- src/extension/analysis/analyzer_das.ts
- src/extension/commands/refactor.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/shared/utils.ts
Fixes #548.
Blocked on https://github.com/microsoft/vscode/issues/43768 being finalised.
> Implement "move file" to support updating references

- package.json
- src/extension/commands/refactor.ts
- src/extension/config.ts
- src/extension/extension.ts
> Rename preview flag for file renames/moves

- package.json
- src/extension/config.ts
> Enable ignore lint quick fix

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/threads.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/debug_helpers.ts
- src/test/helpers.ts
- src/test/test_projects/hello_world/bin/inspect.dart
> Print variables sent to dart:developer's inspect() to the debug console

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/extension/commands/debug.ts
- src/extension/utils/vscode/debug.ts
- src/shared/constants.ts
> Switch dart.progress for DAP progress events

- src/shared/services/stdio_service.ts
- src/test/dart/services/stdio_service.test.ts
> Handle messages terminated with only \r

- src/shared/vscode/color_range_computer.ts
- src/test/flutter/decorations/flutter_colors.test.ts
Also handle whitespace and multi-line breaking.
Fixes #2606.
> Only read first color per line

- package.json
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/extension/config.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/capabilities/flutter.ts
> Add an option to set the Dart Debug extension backend protocol

- package.json
- src/extension/commands/test.ts
- src/extension/extension.ts
- src/shared/constants.ts
> Add "Go to Tests" to explorer context menu, and prompt to create a test file if it doesn't exist

- src/extension/commands/debug.ts
- src/extension/sdk/dev_tools/manager.ts
- src/shared/constants.ts
> Prompt for DevTools page / open in browser when running openDevTools

- src/debug/flutter_debug_impl.ts
- src/debug/run_daemon_base.ts
- src/extension/commands/debug.ts
- src/extension/extension.ts
- src/extension/flutter/hot_reload_save_handler.ts
- src/shared/capabilities/flutter.ts
> Delegate hot-reload debouncing to Flutter when supported

- package.json
- src/extension/commands/debug.ts
- src/extension/commands/test.ts
- src/extension/extension.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/utils.ts
- Show a run/debug button in the editor toolbar for valid target files
- Add automatic launch configurations for detected project/launch types (Flutter, Dart CLI, Test, Dart web)
> Improve initial debug/run experience with debug buttons and automatic launch configs

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/extension/commands/debug.ts
- src/extension/flutter/vm_service_extensions.ts
- src/shared/enums.ts
Adds a "**Flutter: Toggle Brightness**" command, which fixes #2697.
> Adds Flutter: Toggle Brightness command

- src/extension/extension.ts
- src/extension/user_prompts.ts
- src/test/dart_create_tests/dart_create.test.ts
> Delay analyzer creation until after projects have been created

- src/extension/sdk/utils.ts
> Add location for Flutter SDK if installed via Snap on Arch Linux

- src/extension/extension.ts
- src/extension/lsp/test_discoverer.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/views/test_view.ts
- src/shared/test/coordindator.ts
- src/shared/test/test_model.ts
- src/shared/test/tree_model.ts
- src/shared/utils.ts
- src/shared/utils/outline_das.ts
- src/shared/utils/outline_lsp.ts
- src/shared/utils/test.ts
- src/shared/vscode/interfaces.ts
- src/test/dart/test/test_view.test.ts
- src/test/dart_debug/debug/dart_test.test.ts
- src/test/dart_debug_client.ts
- src/test/debug_helpers.ts
- src/test/helpers.ts
- src/test/test_projects/hello_world/test/discovery_test.dart
- tsconfig.build.json
- tsconfig.json
> Populate test tree from Outline information as files are opened

- package.json
- src/extension/commands/sdk.ts
- src/extension/config.ts
> Remove AndroidX flag

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test_debug_impl.ts
- src/debug/web_debug_impl.ts
- src/debug/web_run.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/sdk_manager.ts
- src/extension/sdk/utils.ts
- src/extension/utils.ts
- src/shared/debug/interfaces.ts
- src/shared/utils/fs.ts
- src/test/debug_helpers.ts
> Simplify DAP variables

- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/shared/capabilities/dart.ts
> Switch from "dart pub run test" to "dart run test:test" for >= v2.12

- package.json
- src/extension/commands/debug.ts
- src/extension/config.ts
> Add config option to determine how to display Hot-progress

- package.json
- src/extension/config.ts
- src/extension/providers/debug_config_provider.ts
> Add option to pass additional flags to flutter run/attach commands

- package.json
- src/extension/views/test_view.ts
- src/shared/test/test_model.ts
- src/test/dart_debug/debug/dart_test.test.ts
> Add Dart: Clear Test Results command

- package.json
- src/extension/views/test_view.ts
- src/shared/constants.ts
- src/shared/enums.ts
- src/shared/test/coordindator.ts
- src/shared/test/test_model.ts
- src/shared/utils/test.ts
- src/test/dart_debug/debug/dart_test.test.ts
> Adds a Run All Skipped Tests command

- package.json
- src/extension/views/test_view.ts
- src/shared/constants.ts
> Support Debug/Run Failed menu item actions on group nodes

- package.json
- src/extension/commands/debug.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/dev_tools/manager.ts
- src/shared/capabilities/flutter.ts
- src/shared/interfaces.ts
- src/shared/vscode/interfaces.ts
- src/test/flutter_debug/debug/flutter_run.test.ts
> Share DevTools server with Flutter

- src/extension/commands/debug.ts
> Only apply config.hotReloadProgress to hot-notifications

- package.json
- src/extension/analytics.ts
- src/extension/config.ts
- src/extension/flutter/hot_reload_save_handler.ts
> Add further granular control over Flutter hot-reloading during saves

- src/extension/commands/sdk.ts
> Filter out spurious version file notifications

- package.json
- src/extension/commands/test.ts
- src/extension/extension.ts
- src/extension/views/test_view.ts
- src/shared/capabilities/flutter.ts
- src/shared/constants.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug/debug/dart_test.test.ts
- src/test/debug_helpers.ts
- src/test/flutter_test_debug/debug/flutter_test.test.ts
- src/test/test_projects/flutter_hello_world/test/widget_test.dart
> Add support for running skipped tests in Flutter projects

- src/extension/commands/sdk.ts
- src/extension/pub/stagehand.ts
- src/extension/sdk/dart/dart_create.ts
- src/extension/user_prompts.ts
- src/shared/capabilities/dart.ts
- src/shared/constants.ts
- src/shared/interfaces.ts
- src/test/not_activated/dart_create/extension.test.ts
> Add support for "dart create" for >= v2.10 SDKs

- README.md
Linking to the snippet shortcuts directly from the readme.
> Make it easier to find what snippets are available

- src/extension/commands/add_dependency.ts
- src/test/dart/pub/add.test.ts
This is work mostly done by @EhsanAramide with a little tweaking and some tests. There are new entries at the top of the package list for entering path/Git dependencies (they'll disappear as soon as you type to filter):
These options will prompt for a path/URL(/etc.), although you can also just paste a URL/path directly into that first prompt and hit `<enter>`.
> Support adding Path and Git dependencies through the Add Dependency command

- package.json
Give every group an order (same-order = alphabetical) 
Before | After
--- | ---
> Fix configuration groups ordering

- src/extension/providers/debug_config_provider.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
This only required a small change to use the generic tools script, as we don't use a separate script for attach, but hopefully this doesn't break anything else.
> Use tools script for internal attach

- src/extension/providers/source_code_action_provider.ts
In the refactored code, I extracted the code action objects for organizing imports and sorting members into separate variables. This approach improves readability and eliminates code duplication.
> did some little code refactor

- src/shared/constants.ts
- src/test/test_projects/hello_world/.vscode/settings.json
References:
- https://github.com/microsoft/vscode/pull/197690
- https://github.com/microsoft/vscode/blob/f06dad8535e4556e97734a83a2eac83ca23af8eb/src/vs/editor/common/config/editorConfigurationSchema.ts#L64-L74
> Update editor.wordBasedSuggestions for VS Code 1.85.0

- package.json
- src/shared/constants.ts
Contributes to https://github.com/flutter/website/issues/10363
> Update flutter.dev links to more reliable destinations

- package.json
- src/extension/config.ts
- src/extension/decorations/closing_labels_decorations.ts
- src/extension/lsp/closing_labels_decorations.ts
Fixes https://github.com/Dart-Code/Dart-Code/issues/3628#.
I'm not sure the `recreateDecorationType` is the right approach here but without it, I could not make the label update when changing the propriety on the settings.
> Closing label customisation

- package.json
- src/extension/analysis/analyzer_lsp.ts
- src/extension/extension.ts
- src/extension/lsp/go_to.ts
- src/shared/analysis/lsp/custom_protocol.ts
- src/shared/capabilities/dart.ts
- src/shared/constants.contexts.ts
Adds a new command when the SDK supports it.
We might want to fix https://github.com/dart-lang/sdk/issues/59584 and bump the version number in capabilities to the one with the fix.
(cc @FMorschel )
Fixes https://github.com/Dart-Code/Dart-Code/issues/5326
> Add "Go to Imports" command

- package.json
- src/extension/views/packages_view.ts
- src/shared/constants.contexts.ts
- src/test/dart/views/packages_view.test.ts
- src/test/helpers.ts
Fixes https://github.com/Dart-Code/Dart-Code/issues/5589
/gemini review
> Add an option to "Open on Pub" to the dependencies tree

- src/shared/vscode/autolaunch.ts
- src/test/dart/debug/autolaunch.test.ts
Include debounce, + better handling of disposals and overlapped triggers.
Fixes https://github.com/Dart-Code/Dart-Code/issues/5621
> Handle file modifications to autolaunch file

- src/extension/commands/test.ts
- src/shared/utils/test.ts
- src/shared/vscode/interfaces.ts
- src/test/flutter/views/packages_view.test.ts
- src/test/flutter_test_debug/debug/flutter_test.test.ts
- src/test/helpers.ts
- src/test/test_projects/flutter_hello_world/example/lib/printer.dart
- src/test/test_projects/flutter_hello_world/example/pubspec.yaml
- src/test/test_projects/flutter_hello_world/example/test/printer_test.dart
- src/test/test_projects/flutter_hello_world/lib/printer.dart
Fixes https://github.com/Dart-Code/Dart-Code/issues/5623
> Add support for collecting coverage from dependencies that exist in the workspace
