Dart-Code/Dart-Code

- src/dart_diagnostic_provider.ts
- src/dart_workspace_symbol_provider.ts
- src/utils.ts
- allow case insensitive search in the workspace symbol dialog
- add some common logic to convert from analysis server locations to vscode ones (fix https://github.com/DanTup/Dart-Code/issues/10)
> Make workspace symbol search case-insensitive

- .vscode/settings.json
- src/analyzer.ts
- specify to use tabs w/ the project
- add a flag to control analysis server traffic logging
- minor tweaks to the logging
Some of the changes are more style related; happy to iterate on this patch.
> adjust console logging; set editing prefs

- package.json
- src/analyzer.ts
- src/dart_diagnostic_provider.ts
- src/dart_hover_provider.ts
- src/extension.ts
- src/file_change_handler.ts
- show analysis status (`Analyzing...`) in the status line when the analysis server is busy
- default showing todos to true (fix #39)
- reanalyze sources when the setting for showing todos changes
- don't call `serverShutdown` - if I understand correctly it's basically a no-op
- fix an issue w/ tooltips where some elements (string constants) would show a small, no content tooltip
- only send overlays for files that the analysis server needs to be aware of
@DanTup, it's a grab bag of work. Probably it for this weekend! I'm excited that Dart's getting a plugin for vscode :)
> Show analysis status in status bar (+ other tweaks)

- src/dart_diagnostic_provider.ts
Subscribe to analysis.flushResults and remove all diagnostics for deleted files.
For issue #33
> Remove diagnostics for deleted files.

- media/pull-inverse.svg
- media/pull.svg
- package.json
- src/channels.ts
- src/extension.ts
- src/project.ts
- src/pub.ts
- add command pub.get, pub.upgrade
- have their output go to a dedicated output view at the bottom (this may not be the best long term UX)
- expose the commands on the navigator context menu, editor context menu, and in the editor toolbar when the pubspec.yaml file is open
These commands are active when editing a yaml file; I couldn't find a way to scope it to just a pubspec.yaml file.
> add command pub.get, pub.upgrade

- src/extension.ts
- src/providers/dart_definition_provider.ts
- src/providers/dart_document_symbol_provider.ts
- src/providers/dart_highlighting_provider.ts
- src/providers/dart_reference_provider.ts
- implement a document highlighting provider
- fix #64 
- wrap some long lines
This uses the same technique as the document symbol provider - it turns on an analysis server notification briefly, waits for some results, turns off the notification, and converts the results to the expected vscode format.
> implement a document highlighting provider

- src/analyzer_status_reporter.ts
- display analysis server crashes
In rare cases, the analysis server can throw fatal errors (stack traces from its own code). We dump these to the devtools console; if the user has the `analyzerDiagnosticsPort` setting on, we also display the error in a dialog.
> display analysis server crashes

- src/debug/debug_impl.ts
- src/debug/sdk_path.ts
- src/extension.ts
@devoncarew How does this look? We stash the SDK during activation and then read it back in the debug adapter. I created a file to hold the read/write functions (although only one is needed on each side it made sense to keep the path in one place) and added a comment about it being used in both places (it's important not to pull in `vscode` etc. or the debugger fails to launch with no useful error!).
If you think is good, we can merge as the solution to #83  in lieu of something better.
> Stash dart SDK path in a temp file so debugger can read.

- src/providers/dart_completion_item_provider.ts
A follow-up to https://github.com/Dart-Code/Dart-Code/pull/111:
- show return types for getters
- change how we calc the completion type icons to use the element kind if available
- show the element type in lower case (instead of the default uppercase)
> some tweaks to code completion

- src/debug/utils.ts
- fix an issue with package: paths on windows - convert backslash package: paths to use forward slashes (fix https://github.com/Dart-Code/Dart-Code/issues/123)
@DanTup
> fix package: paths for the debugger on windows

- src/debug/debug_impl.ts
- src/debug/debug_protocol.ts
Fix an issue w/ a race condition at start. For small applications, we could connect after isolates had already been created.
> fix race condition at debugger start

- package.json
- src/commands/type_hierarchy.ts
- src/extension.ts
- implement a type hierarchy command (some code borrowed from the type hierarchy branch)
- fix https://github.com/Dart-Code/Dart-Code/issues/133
This shows the direct supers and all children in a flat list - supers above and children below. The names if implements and mixins are show in the item descriptions but they are not represented as separate elements in the selection list.
@DanTup
> implement a type hierarchy command

- package.json
- src/providers/dart_hover_provider.ts
- remove some pre vscode 1.6 code - hovers in 1.6 better support longer hover docs
@DanTup
> remove code to work around a pre 1.6 issue

- CHANGELOG.md
- README.md
- package.json
- src/analyzer_status_reporter.ts
- src/config.ts
When the analysis server reports an exception, offer to report it as a bug on dart-lang/sdk.
The report looks something like this:
```
Please report the following to https://github.com/dart-lang/sdk/issues/new:
Exception from analysis server (running from VSCode)
<please describe what you were doing when this exception occurred>
- SDK 1.21.0-dev.3.0
- Visual Studio Code
- Dart Code 0.14.0-dev
stack overflow 
'''
foo:123
bar:435
'''
```
> offer to report analysis server errors

- src/analyzer_status_reporter.ts
Some tweaks to the exception report:
- trim extra whitespace
- make the subject line for the report a bit more terse
- remove an obsolete TODO:
Also, I noticed that the reported value for the dart sdk version was `null`, but did not see an obvious reason for it. The status line contribution for the sdk version was correct (non-null).
@DanTup
> tweaks to the exception report

- src/analysis/analyzer.ts
@DanTup, fix a bug with passing additional args to the analysis server - the args weren't being passed to process creation.
Also, filter some analysis server logging from the json stream.
> fix a bug with passing additional args to the analysis server

- src/analysis/analyzer.ts
- src/analyzer_status_reporter.ts
When reporting a server error received from a request, record the server method that we'd called.
```
While responding to request: `foo.bar`
```
Also, fix an issue where when we report the server error, we didn't complete the handler (with the error).
> record the request we were responding to

- src/extension.ts
- src/utils.ts
Fixes #286
Also fixed a minor annoyance of Dart-Code offering to update the Dart SDK when Flutter rolls their own.
> Added ability for findDartSdk to use the Flutter cached version.

- syntaxes/dart.json
Addresses #308.
This is the best solution I could come up with, short of making massive additions to the grammar. :smile:
> Syntax Highlighting: Allow $ in identifiers.

- syntaxes/dart.json
Simplified it to allow quote characters, and not require a Dart variable name.
Potential fix for #305
> Altered string_interp regex

- src/debug/dart_debug_impl.ts
I think this is a place where the tsc compiler's inference was falling down, but in any case, this should make the bots happier.
> fix a tsc type error

- .gitignore
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- show async stack frames when debugging - prefer to use the `asyncCausalFrames` field when that's available, and represent async gap marker frames as blank frames names `<asynchronous gap>`
- fix https://github.com/Dart-Code/Dart-Code/issues/259
- improve the text of stack frames (use the value from the code ref instead of the function name)
@DanTup
> show async stack frames when debugging

- src/extension.ts
- src/utils.ts
This adds some basic fuchsia support.
* Detect if the workspace root is under fuchsia tree.
* Detect Flutter / Dart SDK locations under fuchsia tree.
* Enable closing tag decoration feature under fuchsia.
> Add Fuchsia support

- CHANGELOG.md
- package.json
- src/config.ts
- src/extension.ts
If you have the angular_analyzer_plugin [1] active, the dart analysis server supports analysis and code completion for AngularDart templates. This PR surfaces this information by registering the same dart providers for html files. This functionality is gated behind a new "analyzeAngularTemplates" option (default: false).
[1] https://github.com/dart-lang/angular_analyzer_plugin
> Support angular template analysis

- src/extension.ts
As of v1.4.0, the FLUTTER_HOME variable is no longer used, in favor of FLUTTER_ROOT. This message told the user to set their FLUTTER_HOME instead of FLUTTER_ROOT.
> Remove text reference to FLUTTER_HOME

- src/utils.ts
This changes the logic for finding the correct Dart SDK location for
Fuchsia.
Also, now the user-defined "dart.sdkPath" setting takes precedence, in
case the auto-detected Dart SDK is not the desired one to use.
> Update the Dart SDK path finding logic for fuchsia

- src/extension.ts
- src/providers/dart_completion_item_provider.ts
Fixes #512 .
I tried to tweak the logic as you described but realized that thanks to completion of `import` statements (which inserts `import '|';` I rarely actually type `import '` or `import "`. So it wasn't doing anything useful for me.
I did try different combinations and settled on the one in this PR. I spent about an hour in the editor working on some Dart code with this setting and (to my personal taste) found it to be exactly what I wanted.
One edge case I found was not related to this change:
In annotations, if I type e.g. `@TestOn(` auto complete is triggered (by `(` character) even though there is nothing to complete in this case. This one is tricky since in some cases an annotation can have named arguments in which case it actually could be useful.
> Added more trigger characters to auto completion

- src/providers/dart_completion_item_provider.ts
Fixes #512 .
This should be a nice improvement on top of what we have.
The only edge case not covered would be when editing text inside existing import statement, but it probably happens not as often as writing a new import.
> Trigger suggest command for import statement completions

- package-lock.json
This PR commits the updated package-lock.json generated by running `npm install` on a fresh checkout of the master branch [which results in a modification of the `"@types/ws"` entry].
> Update package-lock to match a fresh install

- package.json
ctrl+f5 is used on mac too (not cmd+f5)
---
If merged this will close #678.
> Add keybinding ctrl+f5 to flutter.fullRestart command

- .vscode/launch.json
- CONTRIBUTING.md
- package.json
- src/extension.ts
- src/providers/debug_config_provider.ts
This means the debugging is much simpler (it just works like the rest of the extension) and we can dynamically pick which DA to start in resolveDebugConfiguration. This may unblock us for folders-in-subfolders and `flutter test`.
Raising as a PR just for testing CodeClimate's integration.
> Switch DAs to be hosted in-process (same as we used to debug)

- src/analysis/analyzer_status_reporter.ts
- src/utils.ts
- test/dart_only/util.test.ts
@devoncarew Please review and let me know what you think... some questions:
1. Is it correct to use the Flutter SDK version when making this decision for a flutter project? It seems strange since the errors are only reported for the analyzer, but if not, all analyzers inside Flutter will be considered dev, since they always have "pre-release" versions (containing hyphens).
2. Is the problem of stable reports being out of date just a consequence of there being no stable releases for so long? Will this change when Dart 2 ships?
3. When Dart 2 ships, won't we see a huge drop in people on dev SDKs and want to revert this?
> Dont report errors in stable sdk

- src/dartdocs.ts
- src/providers/dart_hover_provider.ts
- test/dart_only/providers/dart_hover_provider.test.ts
> Remove class name prefixes from tooltips

- package.json
- src/commands/debug.ts
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/flutter/device_manager.ts
- src/providers/debug_config_provider.ts
- src/sdk/status_bar_version_tracker.ts
See #739.
@devoncarew Please take a look. I'm a little skeptical about the numbers - this reads like "6MB of 9MB" when I run the stocks example app (iOS simulator)... Does this seem in the right ballpark? I'm surprised anything would consume that little memory these days when my editor consumes GBs!
> Add memory usage to status bar

- package.json
- src/utils.ts
- test/dart_only/debug/dart_cli.test.ts
- test/helpers.ts
Since we're often developing in branches that require newer versions of Code (Insiders), this will skip the tests quietly if they can't run in that version of code. This'll stop us getting red crosses on all open PRs targetting the next version.
> Skip tests requiring newer version of VS Code

- src/analysis/analyzer.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test.ts
- src/debug/utils.ts
- src/flutter/flutter_daemon.ts
- src/services/stdio_service.ts
This implements #877 as requested by @kevmoo.
We already have an env var we pass for flutter (which sets `FLUTTER_HOST`). Rather than adding more and having to make sure they were used int he correct places, I've made a single env variable which sets both `FLUTTER_HOST` and `PUB_ENVIRONMENT` and then is used inside `safeSpawn` (which is the function we always use for spawning processes to handle Windows path escaping issues).
In theory, this should solve all the requirements (including that when Pub is invoked by Flutter, assuming it passed the env through).
Does this sound reasonable? Are there any problems with sending both of these all the time?
@kevmoo I assumed the note about test runs was for Dart Code's tests (and not end users tests) but if this is incorrect, let me know. …
> Set environment variables for Pub

- src/debug/dart_debug_impl.ts
Passes initial thread pause states through the same handling as when
they are received as Debug events. This is should have no effect on
'launch' mode, where these states would not be encountered, but
will improve future 'attach' handling.
> Handle initial thread states other than PauseStart

- src/debug/dart_debug_impl.ts
- test/dart_only/debug/dart_cli.test.ts
This seems to be the cause of flaky tests; we sometimes get a PuseStart event after we just resumed at startup. If we hit an exception quickly, then that rogue resume causes a resume from the exception, messing up tests.
Fixes #831.
> Track paused state so we don't unpause twice at startup

- package.json
- src/commands/debug.ts
- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_test_debug_impl.ts
- src/debug/utils.ts
- src/providers/debug_config_provider.ts
- test/dart_only/debug/dart_cli.test.ts
- test/debug_client.ts
- test/debug_client_ms.ts
- test/debug_helpers.ts
- test/flutter_only/debug/flutter_run.test.ts
- test/flutter_only/debug/flutter_test.test.ts
- test/helpers.ts
> Add support for attaching to process

- package.json
- src/config.ts
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/providers/debug_config_provider.ts
@devoncarew @stuartmorgan I made some changes to the debugger to support finding the `.packages` file from the `rootLib` (to aid attaching) but it's based on the assumption that we'll always get an isolate with a `rootLib` (and that the first one that does, if there are many, is the one we're interested in). Does this sound like a valid assumption?
Another option is we always use the `.packages` from the open folder, but this means if you attach a project you don't have open, weird things might happen.
Assuming this is ok, it might also be a step towards being able to open VS Code and attach to a Dart project (and from there, debug the source) without first opening the folder (however, that'll obviously come with limitations, as you won't have the folder open in explorer, and I don't …
> Attach to dart without declaring a path to the .packages file

- src/providers/assist_code_action_provider.ts
- src/providers/dart_reference_provider.ts
- src/providers/fix_code_action_provider.ts
- src/providers/legacy_dart_workspace_symbol_provider.ts
- src/providers/refactor_code_action_provider.ts
Similar to the fix for #930. Sometimes Code changes break our providers because the shape of an object changes. If we use the constructors provided, any type checks will continue to pass.
> Change providers to create instances of types rather than returning objects that implement them

- src/debug/dart_debug_impl.ts
- `<async gaps>` are now centered labels
- frames with no source are left-aligned italic labels (I don't know in what cases these exist)
- non-debuggable sources are greyed out (see https://github.com/Dart-Code/Dart-Code/issues/713#issuecomment-391296941)
> Improvements to call stack rendering

- package-lock.json
- package.json
- src/utils/log.ts
- test/dart_only/commands/complete_statement.test.ts
- test/dart_only/commands/go_to_super_method.test.ts
- test/dart_only/commands/organize_imports.test.ts
- test/dart_only/commands/sort_members.test.ts
- test/dart_only/debug/debug_config_provider.test.ts
- test/dart_only/outline_tracking.test.ts
- test/dart_only/providers/dart_diagnotics_provider.test.ts
- test/dart_only/providers/dart_document_symbol_provider.test.ts
- test/dart_only/providers/dart_formatting_edit_provider.test.ts
- test/dart_only/providers/dart_hover_provider.test.ts
- test/dart_only/providers/dart_rename_provider.test.ts
- test/dart_only/providers/dart_type_formatting_edit_provider.test.ts
- test/dart_only/providers/dart_workspace_symbol_provider.test.ts
- test/dart_only/providers/fix_code_action_provider.test.ts
- test/dart_only/providers/snippet_provider.test.ts
- test/dart_only/refactors/extract_method.test.ts
- test/flutter_only/providers/completion_item_provider.test.ts
- test/flutter_only/providers/dart_document_symbol_provider.test.ts
- test/flutter_only/providers/fix_code_action_provider.test.ts
- test/flutter_only/providers/snippet_provider.test.ts
- test/flutter_only/refactors/extract_widget.test.ts
- test/helpers.ts
- test/mocha_logging_reporter.ts
- test/mocha_multi_reporter.ts
- test/test_runner.ts
This swaps the multi-reporter package for a custom class which allows us to add our own reporters easily, and adds a reporter that writes the test events to the main logfile (this is so we can see the test exceptions in the log files linked from the test dashboard since we can't easily link to the Travis/AppVeyor results because they don't have guessable URLs).
> Add custom mocha reporter to write test status to main log files in CI builds

- src/commands/debug.ts
Commands like hot reload will be sent to all (not ideal, but we can't match a debug session to the workspace folder - I'll improve if https://github.com/Microsoft/vscode/issues/51785 gets implemented), but we will track each session individually. Commands like "Open Observatory" will prompt for which debug session when there's more than one.
Fixes #447.
> Support concurrent debug sessions better.

- package.json
- src/commands/go_to_super.ts
- src/extension.ts
- src/providers/dart_implementation_provider.ts
- src/utils/outline.ts
- test/dart_only/providers/dart_implementation_provider.test.ts
- test/helpers.ts
- test/test_projects/hello_world/lib/go_to_implementation.dart
cc @xster :-)
Not sure if I did this exactly as you desired, so feel free to review the tests below and add comments. It will return all implementations (including where the implementation is overridden, or the class is extended multiple levels). It only ever looks down the hierarchy. 
I also improved up Go to Super to support classes while I was at it (so if you're in a long class you can jump to the super class easily) since there was a lot of overlap in these and code extracted/shared.
> Implement go to implementation

- package-lock.json
- package.json
- src/analysis/analyzer.ts
- src/config.ts
- src/extension.ts
- src/sdk/utils.ts
- src/utils.ts
In certain environments, it is preferable to modify files remotely over
SSHFS, rather than copying dart files locally. In my case, corporate
policies prevent me from copying source files to a laptop. However, I am
allowed to mount directories from my workstation using SSHFS. Dart-Code
works out of the box this way, but its performance is severely limited
by the analysis server needing to crawl the entire source tree over
SSHFS.
Because the analysis server communicates over STDIN/STDOUT, it is
trivial to instead launch the analysis server on a remote machine using
SSHFS. Other SDK integrations such as flutter and fuschia will not work
properly in these environments, but just launching the analysis server
for code intelligence works wonderfully. The only additional limitation
for such an …
> Support launching the analysis server on a remote machine over SSH

- src/providers/debug_config_provider.ts
> Don't try to launch using `flutter` if we never loaded Flutter

- package.json
- src/commands/sdk.ts
- src/config.ts
> Add Flutter screenshot command

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
This fixes #1155 though I'm not entirely sure why (I don't understand what caused it). This splits out disconnect code into the two requests VS Code now sends (terminateRequest when the user first hits stop then disconnectRequest if they hit it again to force a kill).
We were already assuming disconnectRequest could be called twice to handle this so it wasn't much of a change.
One thing I had to remove was our eager sending of TermiantedRequest when the Observatory port closed. This was resulting in VS Code moving on to the disconnectRequest even though terminateRequest was still ongoing. I'm not sure why this code was added, it doesn't seem like we should be considering the process to be exited if it hasn't (if Observatory dies but the process remains running, probably we want to know …
> Support terminateRequest for better handling of graceful/forced shutdown of debugger

- src/commands/edit.ts
We can't calculate a range for a file that's not open and we don't want to create the file manually because it won't be atomic with the edits. We hope we'll never get edits for a new file that aren't at 0/0.
Fixes #339.
> Allow creation of files that don't exist if the edit range is 0/0 (Requires VS Code 1.26)

- src/debug/utils.ts
We removed this in #479 because it was causing breakpoint misses; however those issues appear to all be fixed. Manual testing on macOS and Windows shows hitting breakpoints before, after hot reload, after hot restart on both platforms (I haven't verified Linux, but this PR will run all the tests at least).
> Always send file:/// for URIs to VM

- package.json
- src/commands/debug.ts
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/utils.ts
- src/extension.ts
- src/flutter/device_manager.ts
- src/flutter/flutter_daemon.ts
- src/providers/debug_config_provider.ts
- test/dart_debug_client.ts
- test/dart_only/debug/dart_cli.test.ts
- test/debug_helpers.ts
- test/flutter_only/debug/flutter_run.test.ts
- test/flutter_only/debug/flutter_run_attach.test.ts
- test/helpers.ts
This adds a new command: `Debug: Attach to Flutter Process` (Fixes #1056).
> Initial implementation of `Debug: Attach to Flutter Process`

- package.json
- src/analysis/analyzer_gen.ts
- src/commands/sdk.ts
- src/config.ts
- src/extension.ts
- src/providers/dart_rename_provider.ts
- src/sdk/flutter_samples.ts
- src/sdk/utils.ts
- src/services/stdio_service.ts
- src/uri_handlers/flutter_sample_handler.ts
- src/utils/array.ts
- src/views/test_view.ts
- test/not_activated/flutter_create/extension.test.ts
- test/test_projects/empty/.vscode/settings.json
Adds a `Flutter: Create Sample Project`:
Selecting one will write the trigger file for a sample then open that folder (in a new window if you already have a project open, reusing the current window if not). It's written to a random temp folder to avoid prompting the user (though not sure whether we'd prefer the other?).
Outstanding:
- ~~Switch to master docs path~~ https://github.com/Dart-Code/Dart-Code/issues/1392
- ~~Should we pre-fetch samples and hide this if we can't get them, or just fail at the time we fetch?~~ Failing at fetch time, to make it clearer when something is wrong
> Allow creation of Flutter samples from the command palette

- src/commands/debug.ts
- src/debug/dart_debug_protocol.ts
- src/debug/flutter_debug_impl.ts
- src/flutter/vm_service_extensions.ts
This listens for `Flutter.ServiceExtensionStateChanged` events and updates the local state for those service extension values.
As part of it, I tidied up a lot of this code so there was less duplication and string IDs all over the place, and extracted the extension state tracking from `debug.ts` into a new file `flutter/vm_service_extensions.ts`.
Also changed the platform override to work more like the others, being a standard toggle (between Android/iOS), and with a request sent when the extension loads to get the default value (since it'll vary by device (it's possible this isn't needed in newer versions of Flutter that transmit them all at the start, but this makes old Flutter work correctly too).
> Sync states for Flutter VM service extensions

- .travis.yml
- src/sdk/utils.ts
Fixes #1424. The previous fix was checking before the symlinks were resolved, whereas this now resolves first, then filters after.
> Skip non-dartlang dart binaries

- src/extension.ts
- src/user_prompts.ts
The prompt will only appear if you don't have the Flutter extension and open a Flutter project. Once you either click **Show Me** or dismiss the notification, it will never be shown again (note: if you just ignore it so VS Code hides it into the notification area without it being dismissed, you will see it again the next time).
> Prompt users (once) to install the Flutter extension when opening a Flutter project if they don't have it

- src/commands/sdk.ts
- test/dart_only/commands/pub_get.test.ts
- test/helpers.ts
Fixes #1427.
@paulcbetts how does this seem to you?
I've uploaded a build here if you want to try it out:
https://github.com/Dart-Code/Dart-Code/releases/tag/v2.23.0-alpha.1.delay-pub-get
Download the vsix and install with `Extensions: Install from VSIX`. It'll auto-update you back to stable once we publish the next release (which will include this if the feedback is good).
> Stop "pub get on save" being super-aggro

- src/analysis/open_file_tracker.ts
- src/code_lens/test_code_lens_provider.ts
- src/commands/test.ts
- src/providers/debug_config_provider.ts
- src/utils.ts
This avoids querying on every keypress now that we need to update the run-test-at-cursor context.
Fixes #1441.
> Keep track of whether a file supports pub-run-test in the file tracker

- src/utils/fs.ts
Reproduce step:
```
// In the project folder's primary directory
touch ln_origin.txt 
ln -s ln_origin.txt ln_linked.txt
rm ln_origin.txt
// open VSCode and activate Dart-Code(Flutter plugin)
```
If there is a soft link file, but the original file is deleted, `fs.statSync`will throw an error and cause the activation to fail.
> Avoid activation failures due to link file errors

- .travis.yml
- appveyor.yml
We normally run combinations of Stable/Stable, Stable/Dev, Dev/Stable, Dev/Dev for (Dart/Flutter) and (VS Code) builds. The Dev/Stable and Stable/Dev don't add massive value, they just make it easier to spot whether it's Dev Dart/Flutter or Dev VS Code that's caused a fail (that also shows up in Dev/Dev).
So, this change skips those combinations for branches, but still runs on master.
> Speed up CI by running less build combinations for branches

- src/analysis/analyzer_status_reporter.ts
- src/analytics.ts
- src/commands/debug.ts
- src/commands/sdk.ts
- src/extension.ts
- src/providers/debug_config_provider.ts
- src/sdk/status_bar_version_tracker.ts
- src/sdk/update_check.ts
- src/sdk/utils.ts
- src/user_prompts.ts
- src/utils.ts
- test/dart_only/extension.test.ts
- test/flutter_only/extension.test.ts
- test/helpers.ts
- test/multi_root/extension.test.ts
ProjectType worked ok when there was only Dart vs Flutter, but now it's becoming more common to have multiple project types (in future you could easily have Dart, Web, Flutter, Flutter Web, Fuchsia workspace folders).
This moves all code that used ProjectTypes directly to instead use flags on a new WorkspaceContext which are not mutually exclusive. This makes it easier to answer questions like "do we need to show the device manager?" which really means "are any projects Flutter mobile?".
> Remove assumptions about there being only one type of project in a workspace

- src/user_prompts.ts
- Fix location of settings on Windows (see https://github.com/dart-lang/usage/blob/5ad6959611dd2f2c504c7a7050a5f770a42203f9/lib/src/usage_impl_io.dart#L63).
- Also don't show if there are no Flutter projects (Dart-only users aren't interested in Flutter surveys)
@pq FYI. I don't think you have this bug (your PR wasn't reading the file directly), but apparently I did (and apparently my subconscious mind can find bugs while I'm making tea that my conscious mind can't while I'm writing the code 🙈).
> Survey fixes

- package.json
- src/debug/flutter_debug_impl.ts
- src/debug/utils.ts
- src/providers/debug_config_provider.ts
`flutter --target-platform` allows developers to choose the target architecture.
It's auto-selected but sometimes there is a definitive need to specify the field sometimes, e.g. App testing for different phones / architectures.
> Add support for target-platform to Flutter launch config.

- package.json
- src/config.ts
- src/decorations/flutter_ui_guides_decorations.ts
- src/editing/trackers.ts
- test/dart_only/editing/position_trackers.test.ts
Adds a `dart.previewFlutterUiGuidesCustomTracking` setting that enables custom tracking of edits to try and keep guides updated while waiting for a Flutter Outline update.
Guide are currently tinted pink when being rendered by this code. If it takes a while for pink guides to go back grey, then there's probably a real benefit to this. If the pink guides are rendered incorrectly, maybe not!
> Add custom tracking to UI Guides preview

- src/extension/analysis/analyzer.ts
- src/extension/providers/dart_completion_item_provider.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_only/providers/completion_item_provider.test.ts
- src/test/flutter_only/providers/completion_item_provider.test.ts
- src/test/test_projects/flutter_hello_world/.vscode/settings.json
- src/test/test_projects/hello_world/.vscode/settings.json
Fixes #1776, though there are still some questions about the logic that need to be checked.
> Filter completions for items that are already imported via another library

- src/extension/sdk/dev_tools.ts
@jacob314 @terrylucas any preference on the name/value of this? Although not technically an IDE, `ide` seemed shorter than `editor`. Using a real `name=value` rather than just `&vscode=` makes it easier to just write as-is to a custom dimension if the other editors did the same.
> Add ide=VSCode to DevTools querystring

- src/extension/extension.ts
- src/extension/providers/ignore_lint_code_action_provider.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_only/providers/dart_formatting_edit_provider.test.ts
- src/test/dart_only/providers/dart_hover_provider.test.ts
- src/test/dart_only/providers/dart_reference_provider.test.ts
- src/test/dart_only/providers/ignore_lint_code_action_provider.test.ts
- src/test/helpers.ts
Does doesn't enable LSP, but is some fixes back-ported (and then tweaked to ensure they didn't break non-LSP).
> Make many tests compatible with running against LSP server

- src/extension/flutter/device_manager.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/flutter/flutter_types.ts
For older versions we just treat every device as auto-selectable, but when Flutter tells us a device is not ephemeral (Desktop/Web) we don't auto-select it unless there are no other devices.
This can be improved further (only auto-select if it's valid for an open project), but this will at least avoid the issue where a desktop device is selected upon opening a project if the mobile is already connected (the devices come through with mobile first, desktop second).
> Only select ephemeral devices

- .travis.yml
- package-lock.json
- package.json
- src/test/remap_coverage.ts
- src/test/test_all.ts
- webpack.config.js
This gets the report mostly working locally, however there are two issues to resolve:
> Fix up coverage after webpacking broke it

- src/extension/debug/dart_debug_impl.ts
- src/extension/debug/dart_debug_protocol.ts
- src/shared/capabilities/vm_service.ts
@devoncarew would you mind scanning these changes? (Select **Hide whitespace changes** in the diff to avoid seeing loads of changes due to indent change!).
Fixes https://github.com/Dart-Code/Dart-Code/issues/1843.
Also see https://github.com/dart-lang/vm_service_drivers/pull/251.
> Use "Service" instead of "_Service" for VM service protocol >= 3.22

- package.json
- src/extension/config.ts
- src/extension/debug/dart_debug_impl.ts
- src/extension/debug/dart_debug_protocol.ts
- src/extension/debug/utils.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/capabilities/vm_service.ts
- src/test/dart_only/debug/dart_cli.test.ts
- src/test/test_projects/hello_world/.vscode/settings.json
- src/test/test_projects/hello_world/bin/main.dart
~~Required to do https://github.com/Dart-Code/Dart-Code/issues/1824.~~ Not so, Flutter's errors come through as `Flutter.Error` and are separate to `dart:developer`'s `log()`. This just exposes logs that would otherwise not be visible to the user.
> Show log events from dart:developer log() in the debug console (if enabled)

- src/extension/debug/dart_debug_impl.ts
I originally missed these out. They're also async, so we need to chain future logs after this to ensure they're printed in the same order.
Fixes #1824.
> Add errors/stacks to dart:developer logging

- package.json
- src/extension/config.ts
- src/extension/debug/dart_debug_impl.ts
- src/extension/debug/flutter_debug_impl.ts
- src/extension/debug/utils.ts
- src/extension/flutter/vm_service_extensions.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/enums.ts
- src/shared/flutter/structured_errors.ts
@jacob314 @InMatrix @devoncarew I've made some progress on this, trying to make them look like IntelliJ's (so please let me know if they change - for ex the yellow ascii banner - so I can copy).
Two of the examples in @InMatrix's repo don't look too bad:
However the Material one looks really bad:
I think probably I'm rendering more nodes than I should (though it's not clear how I should decide which to show), but also some of it's just in the source (like the top line is like this in one big string). How should that be handled?
> Use Fluttered structured error events (behind preview flag)

- src/extension/extension.ts
- src/extension/providers/dart_document_symbol_provider.ts
To better support analyzer plugins on custom file endings, I've made two changes:
1. Register providers that aren't specific to Dart (all those we register on `MODE_HTML`) for extensions declared in `additionalAnalyzerFileExtensions` if the option to use the Angular plugin is turned on.
2. Use the analysis server folding for both html and custom files if enabled.
With a plugin I'm writing, I could verify that auto-complete, folding, outline, problems, fixes and navigation are all working with this setup.
Fixes #1981
In the linked issue, you asked whether the analysis server would send problematic responses when used with unsupported files. I played around with this as the plugin was turned off, and I didn't run into any problems.
Further, that shouldn't have any impact on the first change …
> Extend analysis to to custom file extensions; folding for non-Dart files

- package.json
- src/extension/config.ts
- src/extension/flutter/hot_reload_save_handler.ts
- src/test/flutter_only/debug/flutter_run.test.ts
This allows reloading automatically when external tools (or Git!) modify files.
Fixes #2074.
> Add a (preview) setting to perform reload-on-fs-change

- package.json
- src/extension/analysis/analyzer_status_reporter.ts
- src/extension/config.ts
@devoncarew @bwilkerson This changes the "generate error report" notifications to just "show log" and removes the header about raising on GitHub. It will still only show a maximum of 3 times per-session (and VS Code will "overwrite" notifications if there's already one visible and we send another with the same message to avoid ever seeing more than one on screen).
We do also already have code to detect if the server terminates and show a notification (with Show Log and Restart Analyzer buttons).
> Change error reporting to just "Show Log"

- package.json
- src/extension/code_lens/flutter_dartpad_samples.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/test/flutter/providers/flutter_dartpad_samples_code_lens_provider.test.ts
This adds CodeLens links for Flutter files that have `{@tool dartpad` snippets that open the interactive online samples:
It has some assumptions/caveats:
- Only works for files inside `(Flutter SDK)/packages/flutter/lib/src/material/app_bar.dart`
- Assumes the leaf-most folder name is the package (eg. in the above, "material") and that the `name` from the `Outline` node is the classname, and uses these in the URL as `${sample.libraryName}/${sample.className}-class.html`
- Always links to `https://api.flutter.dev` regardless of your Flutter branch/channel
- Assumes there's an element with the ID `#${sample.libraryName}.${sample.className}.1` at the correct location (this jumps down the page - if this assumption becomes invalid, you'll end up at the top of the docs page for that class) …
> Add CodeLens links for Flutter DartPad samples

- src/shared/constants.ts
- src/shared/vscode/user_prompts.ts
- src/shared/vscode/workspace.ts
- src/test/dart/user_prompts.test.ts
- src/test/helpers.ts
@pq @jayoung-lee FYI. A lot of the change here is just renaming the fields (so we don't reuse values from previous surveys). The date/link change is in the second commit (5a09f8e69ba983a95b357b3107680bc37cf67dc9).
> Add Flutter 2020 Q1 survey details

- src/shared/constants.ts
@pq @jayoung-lee FYI!
Note: I changed the close time from 5pm to 4pm UTC because otherwise it came out at 10am (because you go into PST?) and wasn't sure if which timezone the survey close date is in (I'd rather stop showing the prompt an hour before it ends than continue an hour after).
> Change Flutter Q1 survey date

- src/extension/services/stdio_service.ts
- src/test/dart/providers/dart_formatting_edit_provider.test.ts
This seems to fix an issue with some unicode characters becoming "broken" which is likely when their bytes split across buffers and we convert them to strings before joining back together.
Fixes #2140.
> Keep stdout buffers to concat instead of converting to strings

- package.json
- src/extension/commands/sdk.ts
- src/extension/config.ts
> Add Create Offline Configuration

- package.json
- src/extension/commands/sdk.ts
- src/extension/extension.ts
- src/extension/sdk/capabilities.ts
- src/shared/constants.ts
- src/shared/vscode/interfaces.ts
- src/test/dart/commands/outdated.test.ts
- src/test/flutter/commands/outdated.test.ts
Fixes #2322, though there may be ways we can integrate this better than just dumping the text to an output window (using `--json`).
> Add support for running "pub outdated"

- package.json
- src/extension/code_lens/main_code_lens_provider.ts
- src/extension/code_lens/main_code_lens_provider_lsp.ts
- src/extension/commands/debug.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/test/dart/providers/main_code_lens_provider.test.ts
- src/test/dart/providers/test_code_lens_provider.test.ts
Fixes #2356.
Can be turned off with the `dart.showMainCodeLens` setting.
> Add code lens for main methods inc templates

- .github/workflows/build-and-test.yml
As mentioned on https://github.community/t5/GitHub-Actions/Duplicate-checks-on-quot-push-quot-and-quot-pull-request-quot/m-p/54956#M9370, this should work with a pull request from a fork. Fingers crossed.
> Remove the hardcoded repo name from the workflow logic

- .github/workflows/build-and-test.yml
This shouldn't be required anymore (see https://github.com/actions/virtual-environments/issues/7).
> Remove Chrome setup from CI

- src/debug/dart_debug_impl.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug_client.ts
- src/test/flutter_debug/debug/flutter_run.test.ts
- src/test/helpers.ts
- src/test/test_projects/hello_world/bin/long_running.dart
Use first thread, since we can't evaluate without one.
Fixes #906.
> Add basic global expression evaluation

- src/debug/dart_debug_impl.ts
> Prevent sending multiple kill signals to the same PID

- .vscode/settings.json
- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_debug_protocol.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/threads.ts
- src/debug/utils.ts
- src/debug/web_debug_impl.ts
- src/extension/analysis/analyzer.ts
- src/extension/commands/debug.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/utils/log.ts
- src/shared/constants.ts
- src/shared/enums.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/debug_helpers.ts
- src/test/flutter_debug/debug/flutter_run_attach.test.ts
Launch configs will support both `vmServiceUri` and `observatoryUri` for a while. Most user-facing strings are updated. The "Open Observatory" command remains as-is for now, as that's still what it does.
Fixes https://github.com/flutter/devtools/issues/1642.
> Update references to "Observatory" to "VM Service" where appropriate

- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
There was a race condition in the debugger connection code. If the thread was in the `PauseStart` state when we first found it, everything worked fine. However if it was in the `None` state initially, and changed to `PauseStart` before we'd finished the rest of the startup code, the event would be dropped (with a warning: "ThreadManager couldn't find thread with ref isolates/1462887175408855 to handle PauseStart").
To fix it, any incoming events wait for the initialisation to complete before being processed.
> Fix debugger initialisation race

- README.md
- src/shared/constants.ts
These were the only two remaining instances I could see in the codebase. Fixes dialogs like this:
> Update from flutter.io to flutter.dev

- src/extension/commands/sdk.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/constants.ts
- src/shared/interfaces.ts
- src/shared/vscode/device_manager.ts
- src/test/flutter/device_manager.test.ts
Devices that are available in Flutter (`flutter devices`) but not supported according to Daemon's `getSupportedPlatforms`) will now be shown in the device picker prefixed with "Enable ":
Selecting one will prompt to run `flutter create .` for you:
Once that completes, it'll select that device for you.
Fixes #2602.
> Include "unsupported" devices in the device picker, offer to run "flutter create ." when selected

- package.json
- src/extension/extension.ts
- src/extension/pub/build_runner_task_provider.ts
Enable previewBuildRunnerTasks in flutter project and then execute
Command Palette > Tasks: Run task > Show all tasks...
You will see this error:
The task provider for "pub" tasks unexpectedly provided a task of type "flutter".
Probably because pub is hardcoded here:
https://github.com/Dart-Code/Dart-Code/blob/b6aac604c02af46d66f99e01650c2b4b50c9edfc/src/extension/extension.ts#L337
So I changed the code to always use "pub".
> Fix "tasks unexpectedly provided a task of type" error

- src/extension/providers/debug_config_provider.ts
The conditionals to determine the debug type to use (eg. Flutter) is too aggressive and prevented the use of a launch path such as `lib/web/myfile.dart` due to being misconstrued as a Web project.
Fixes #2690.
> Fixes Flutter app from being incorrectly set as a Web debug target

- .vscode/launch.json
- package.json
- src/debug/dart_debug_entry.ts
- src/debug/dart_test_debug_entry.ts
- src/debug/debug_entry.ts
- src/debug/flutter_debug_entry.ts
- src/debug/flutter_test_debug_entry.ts
- src/debug/web_debug_entry.ts
- src/debug/web_test_debug_entry.ts
- src/extension/extension.ts
- src/extension/providers/debug_adapter_descriptor_factory.ts
- src/shared/constants.ts
- src/shared/utils/debug.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_debug_client.ts
- src/test/debug_client_ms.ts
- src/test/debug_helpers.ts
- src/tool/generate_launch_configs.ts
- tsconfig.json
- webpack.config.js
When running in-process these were all packed, but we lost that when running out-of-process. This packs into a single debug adapter that takes an argument for the debugger name (to avoid having many entry points all being built with webpack that are mostly the same).
> Switch to a single webpack'd debug adapter

- src/extension/sdk/flutter.ts
- src/extension/sdk/utils.ts
- src/shared/constants.ts
If Flutter is missing the `version` file or `bin/cache/dart-sdk`, this will show an "initializing..." notification (same as Snap support already did) and delay activation until that's done. This prevents some weird edge cases (including #2638) where we might initialize badly.
@MarcusTomlinson this shouldn't change anything for snap (and the CI tests still pass), it's mostly just making some of its code reusable - but FYI! (I'll likely make a beta build including this in the next few days).
> Tweaks to Flutter initialization

- src/extension/decorations/flutter_ui_guides_decorations.ts
Fixes the tilting, but there may be a visual artifact due to the guidelines vertically overlapping (see included screenshot).
Fixes #2239.
> Stop Flutter UI guidelines being tilted for certain fonts

- package.json
- src/extension/commands/test.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/views/test_view.ts
- src/shared/constants.ts
- src/shared/utils.ts
- src/shared/utils/test.ts
- src/test/dart_debug/debug/dart_test.test.ts
- src/test/helpers.ts
- src/test/test_projects/hello_world/test/broken_test.dart
> Add option to re-run only failed tests

- package.json
- src/extension/commands/logging.ts
- src/extension/utils/log.ts
- src/test/dart/commands/capture_log.test.ts
- src/test/test_projects/hello_world/pubspec.yaml
Splits the _Capture Logs_ command into multiple commands:
* **Capture Logs**: Selectable capture categories via a picker, as before.
* **Capture Analysis Server Logs**: Only captures _Analyzer_ and _CommandProcess._
* **Capture Debugging Logs**: Captures everything except _Analyzer._
* **Capture Extension Logs**: Captures only _CommandProcess, DevTools,_ and _FlutterDaemon._
Includes tests.
Fixes #2789.
> Capture logs

- src/shared/logging.ts
- src/test/helpers.ts
> Include logged categories in log file header

- package.json
Adds a `dart.showDevToolsDebugToolBarButtons` boolean that determines whether to show the `dart.openDevToolsInspector` and `dart.openDevToolsTimeline` buttons within the DevTools ToolBar.
Fixes #2836.
> Add DevTools ToolBar buttons config toggle

- package.json
- src/extension/config.ts
- src/extension/providers/debug_config_provider.ts
Adds `flutterTestAdditionalArgs` configuration parameter, that enables customizing `flutter test` command with custom arguments (like `--coverage` or `--exclude-tags`).
Fixes #2915
> Add flutterTestAdditionalArgs setting

- package.json
It's election day and I can't focus on complicated tasks today, so I'm investing some time in tidy-up work instead. 
This pull request attempts to clean up some of the settings descriptions for the extension:
- Uses [`markdownDescription`](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) where appropriate to add hyperlinks and `code fences`
- Replaces "folder" with "directory"; "application" with "app" per [Google developer style guide](https://developers.google.com/style/word-list)
- A few minor grammar nits or clarifications where I believed they improved the text
I've tested this locally by running in the extension development host to make sure the changes are presented correctly in `launch.json` and the settings editor.
> Update inline descriptions for DartCode settings

- src/extension/sdk/status_bar_version_tracker.ts
Does not show the Dart-centric VS Code label if the active document is HTML.
Fixes #2984.
> Not show Dart-specific label for HTML documents

- src/extension/commands/sdk.ts
- src/test/not_activated/dart_create/extension.test.ts
- src/test/not_activated/flutter_create/extension.test.ts
- Pre-fills name upon creating a new project. Project name determination only occurs for the initial, pre-filled name suggestion and will not apply if a different name is entered entirely.
- Displays an in-place error during (user input) project naming should a directory with the specified name already exist. This negates the user needing to reinvoke the create-project command to begin creating a project again.
- Optimises out multiple `fsPath`() calls.
> Prefilled project name

- package.json
- src/extension/commands/sdk.ts
- src/extension/user_prompts.ts
- src/shared/interfaces.ts
- src/shared/utils/projects.ts
- src/shared/vscode/flutter_samples.ts
- src/test/flutter_create_tests/extension.test.ts
- src/test/flutter_create_tests/flutter_create.test.ts
- src/test/not_activated/flutter_create/extension.test.ts
- src/test/test_projects/flutter_create_module/flutter.create
- src/test/test_projects/flutter_create_package/flutter.create
- src/test/test_projects/flutter_create_plugin/flutter.create
- src/test/test_projects/flutter_create_sample/flutter.create
- src/test/test_projects/flutter_create_tests.code-workspace
This currently only implements the `module` template; if it looks good, then there will additional commits implementing the `plugin` and `package` templates.
Fixes #2963.
> Add support for creating other Flutter project templates

- package.json
- src/extension/config.ts
- src/extension/dart/dart_task_provider.ts
- src/extension/extension.ts
- src/extension/flutter/flutter_task_provider.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/capabilities/flutter.ts
- src/shared/flutter/utils.ts
This adds a setting to easily set the web renderer at the User Setting or Workspace Setting level. It will be injected into `flutter run` commands (launched via the debugger) and `flutter build web` tasks (from the Flutter task contributions) unless they already have this in their `args`.
Fixes #2999.
> Add a setting to easily set Flutter's web renderer in user/workspace settings

- src/shared/utils/fs.ts
Prevents the `.dart_tool` folder from appearing within the **Flutter: Upgrade Packages** list.
Fixes #3013.
> Exclude .dart_tool folder from upgrade packages list

- media/commands/test-clear-dark.svg
- media/commands/test-clear-light.svg
- media/commands/test-run-failed.svg
- media/commands/test-run-skipped.svg
- package.json
- src/extension/config.ts
- src/extension/views/test_view.ts
- src/shared/test/coordindator.ts
- src/shared/test/test_model.ts
- src/test/dart_debug/debug/dart_test.test.ts
This is progress towards #3038 and #3050 but will need rebasing over @BootBlock's PR.
Still needs:
(Fixes #3038 and fixes #3050 once complete.)
> Add new test commands/settings

- src/extension/commands/test.ts
- src/extension/views/test_view.ts
Fixes incorrect parameters being passed to `getLaunchConfig`.
Fixes #3097.
> Pass --run-skipped when running a test from the test tree/code-lens

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/extension/commands/debug.ts
- src/extension/config.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/dev_tools/manager.ts
- src/shared/constants.ts
- src/shared/debug/interfaces.ts
- src/shared/flutter/structured_errors.ts
- src/shared/interfaces.ts
> Extract devtools links from flutter structured errors

- src/extension/extension.ts
- src/extension/views/test_view.ts
- src/shared/test/coordinator.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_debug_client.ts
Fixes all instances of `coordindator` appearing rather than `coordinator`.
> Fix typo in Coordindator naming

- package.json
- src/extension/commands/test.ts
- src/extension/extension.ts
- src/extension/utils.ts
- src/extension/views/test_view.ts
- src/shared/constants.ts
- src/shared/test/test_model.ts
- src/shared/utils/test.ts
- src/test/dart_debug/debug/dart_test.test.ts
Applies to Dart-only projects as Flutter doesn't support --run-skipped.
Fixes #3097, #3107, #3048.
> Add the ability to "Run all Skipped Tests" for Dart projects

- package.json
- src/extension/analysis/analyzer_lsp.ts
- src/extension/analysis/analyzer_lsp_snippet_text_edits.ts
- src/extension/config.ts
- src/shared/capabilities/dart.ts
- src/test/flutter/providers/assist_code_action_provider.test.ts
> Add support for the LSP SnippetTextEdits unofficial extension

- src/extension/sdk/flutter.ts
- src/extension/sdk/utils.ts
- src/shared/constants.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_snap/extension.test.ts
Fixes #2853.
@MarcusTomlinson FYI - this is to remove a lot of the snap-specific code that should no longer be required (https://github.com/canonical/flutter-snap/issues/8).
There is still a _little_ code to detect where a user has never invoked `flutter` so it hasn't been initialised, which is in the block here:
https://github.com/Dart-Code/Dart-Code/pull/3292/files?diff=split&w=1#diff-a4ef2b6ac3b51b2727e1fdae4a827f588e33df8c71bbad63fde3b96a92b5bfd1R265
It detects when no Flutter SDK is found, but there is a `flutter` binary that is a symlink to the Snap binary (it seems like this is created by Snap initially, so that the first run of `flutter` will trigger the initialisation), forces initialisation, and then re-searches for the SDK (since after initialisation, there is a _new_ `flutter` …
> Reduce the amount of Snap-specific code requires to set up Flutter

- package.json
Hey @DanTup.
I just saw your fix for #3315. Thanks for that!
I also noticed the "Launch Emulator" command wasn't available in remote workspace. I guess this is because of the `when` clause in `"package.json"`: https://github.com/Dart-Code/Dart-Code/blob/f38e02c2e3384975d4d051484836a7984e31d64d/package.json#L987-L988
I supposed this simple additional condition using the new configuration parameter would allow to run the command in a devcontainer.
Thoughts?
> Support launching emulator devices in remote workspaces

- src/extension/pub/global.ts
- src/extension/sdk/dev_tools/manager.ts
- src/extension/sdk/utils.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/debug/flutter_run.test.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/flutter_snap/extension.test.ts
- src/test/test_projects/bazel_workspace/flutter_hello_world_bazel/dart/config/intellij-plugins/flutter.json
- src/test/test_projects/bazel_workspace/scripts/custom_devtools_activate.sh
- src/test/test_projects/bazel_workspace/scripts/custom_devtools_run.sh
This is to clean up VSCode's view of flutter.json, which has changed significantly since this was last updated. This simplifies DevTools startup since we no longer have a separate script to start DevTools; this may change in the future to either using the daemon (see comments for more details) or another method.
> Match latest flutter.json

- src/extension/flutter/flutter_daemon.ts
- src/shared/capabilities/flutter.ts
- src/shared/flutter/daemon_interfaces.ts
- src/shared/interfaces.ts
- src/shared/vscode/device_manager.ts
- src/test/flutter/device_manager.test.ts
This pull request adds a cold boot option to each android based emulator.
The command palette looks as follows:
closes #3366
> Add coldboot option to AVD emulators

- src/extension/sdk/utils.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/debug/flutter_run.test.ts
I think for now it'll be okay to assume that any internal workspace is a Flutter workspace, since the added functionality (showing device menu in this case) doesn't interfere with other workspaces. We may want to change this later to require an indication of Flutter in a `.code-workspace` file.
The internal "Flutter SDK" path isn't really a path with a binary to run Flutter, since we rely on scripts to execute the equivalent  flutter commands instead, but it is necessary that we are in the right working directory to execute the scripts. Versioning isn't important since we can assume all internal users will be on a close to the latest version or will update if not.
The script for running a daemon to find devices can have stdout that results in lines like: `[3:27:46 PM] [FlutterDaemon] …
> Enable device daemon for bazel workspace (WIP)

- src/extension/sdk/status_bar_version_tracker.ts
- src/extension/sdk/utils.ts
- src/shared/constants.ts
- src/shared/interfaces.ts
- src/shared/utils.ts
- src/shared/utils/fs.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/test_projects/bazel_workspace/flutter_hello_world_bazel/dart/config/intellij-plugins/flutter.json
The version file isn't needed for bazel projects, so just setting it to latest. I may be able to remove the `flutterVersionFile` completely.
> Set bazel project flutter SDK version to latest

- .github/workflows/build-and-test.yml
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/shared/capabilities/dart.ts
- src/test/dart/providers/dart_signature_help_provider.test.ts
- src/test/flutter_debug/debug/flutter_run.test.ts
With these changes the bots should start passing once the `--no-serve-devtools` change reaches a published Dart SDK dev build.
Edit: Also requires some solution to https://github.com/dart-lang/sdk/issues/46274 and that rolled into dev.
> Use --no-serve-devtools and re-enable dev tests

- src/debug/flutter_debug_impl.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/utils.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
I needed only minor changes for a basic bazel run app configuration to work, but there are probably other situations where bazel will differ from a standard app due to things like:
- Excluding some arguments
- Arguments having a different flag name
- I think the change in ordering I made for where the target is passed is okay for standard apps too, but if not, argument order may need to be adjustable
Maybe some of these differences could be codified in the workspace, e.g. have an 'arguments' JSON that looks like:
```
{"arguments": [
{"device": {}},
{"mode": {"replaceFlagName": "otherMode"}},
{"target": {"excludeFlagName": "true"}
] }
```
Alternatively, I could add an internal script that translates from standard arguments to the arguments we need. That would be more flexible but seems …
> Switch arg order for rudimentary bazel run

- package.json
- src/debug/dart_debug_impl.ts
- src/debug/dart_test_debug_impl.ts
- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test_debug_impl.ts
- src/debug/web_debug_impl.ts
- src/debug/web_test_debug_impl.ts
- src/extension/config.ts
- src/extension/flutter/flutter_task_provider.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/capabilities/flutter.ts
- src/shared/debug/interfaces.ts
- src/shared/flutter/utils.ts
- src/shared/utils.ts
- src/shared/utils/array.ts
- src/shared/utils/test.ts
- src/test/dart/util.test.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/debug_helpers.ts
- src/test/flutter_debug/debug/flutter_run.test.ts
- src/test/helpers.ts
This simplifies the debug adapters somewhat (reducing the amount of work needed for SDK-based debug adapters) and makes it easier for the client to customise.
Args are now passed to the DA in two fields:
- `args`: user-args that are generally passed to the script
- `toolArgs` args passed to the VM or Flutter tool
The difference is that the users `program` is generally inserted in between them:
- `dart [toolArgs] foo.dart [args]`
- `flutter run [toolArgs] --target foo.dart [args]`
- `flutter test [toolArgs] test/foo_test.dart [args]`
> Move lot of argument building from Debug Adapter into extension

- src/extension/commands/debug.ts
- src/extension/extension.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/sdk/dev_tools/manager.ts
- src/shared/flutter/daemon_interfaces.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter/device_manager.test.ts
This sets up a running DevTools server using a script specified in the workspace, but trying to get the embedded inspector page fails with "Dart DevTools was unable to launch Chrome so your default browser was launched instead", along with "Request must contain a "method" key." (I don't see a default browser opening either)
I see that this logic goes through `launchInEmbeddedWebView` but I'm not sure what parameters are expected here for a successful launch and not sure what I may be missing.
Also, is there a hook on workspace close to shut down the daemon process?
> Use daemon to start bazel DevTools (WIP)

- package-lock.json
- package.json
- src/test/test_all.ts
vscode-test be marked as [deprecated](https://www.npmjs.com/package/vscode-test) on npmjs.org(yarnpkg.com), so just replace vscode-test with latest @vscode/test-electron for `Dart-Code`'s CI. cc @DanTup
> chore: replace deprecated vscode-test with @vscode/test-electron

- package.json
- src/extension/commands/add_dependency.ts
- src/extension/commands/packages_add.ts
- src/extension/extension.ts
- src/extension/providers/add_dependency_code_action_provider.ts
- src/extension/utils/vscode/projects.ts
- src/shared/fetch.ts
- src/shared/pub/api.ts
- src/shared/pub/pub_add.ts
- src/shared/vscode/interfaces.ts
- src/shared/vscode/workspace.ts
- src/test/dart/pub/add.test.ts
- src/test/flutter/pub/add.test.ts
- src/test/helpers.ts
Possible future improvements:
Fixes #3306.
>  Add a "Dart: Add Dependency" command

- src/shared/vscode/color_range_computer.ts
This pull request adds support for hexadecimal values with a uppercase letter x in the prefix. For example, `0XFFFFFFFF` instead of a lowercase x `0xFFFFFFFF`.
> Add support hexadecimal uppercase x

- src/debug/flutter_debug_impl.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
I had wanted to use only main files as targets to minimize divergence from the external workflow, but it would be nice to have an exception for now. It will take more time to investigate how much work it would be to get teams to change their configurations to using main files only.
> Allow bazel target that's not a main file

- src/extension/sdk/dev_tools/embedded_view.ts
See https://github.com/flutter/devtools/issues/3251 - external links are currently failing when DevTools are embedded in VSCode due to the "allow-popups" sandbox restriction being enabled.
There might be a simpler solution to this that I'm unaware of.
I'm not very experienced with VSCode/TypeScript development, please check carefully 😁
Especially not sure if I got the dispose logic right.
Buddy PR on DevTools: https://github.com/flutter/devtools/pull/3252
> Add support for DevTools to open external links

- package.json
- src/extension/commands/test.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/flutter/flutter_outline_view.ts
- src/extension/providers/debug_config_provider.ts
- src/extension/test/vs_test_controller.ts
- src/extension/utils.ts
- src/extension/views/test_view.ts
- src/shared/debug/interfaces.ts
- src/shared/test/coordinator.ts
- src/shared/test/test_model.ts
- src/shared/vscode/interfaces.ts
- src/test/dart/test/test_view.test.ts
- src/test/dart_debug/debug/dart_test.test.ts
- src/test/dart_debug_client.ts
- src/test/flutter/views/flutter_outline.test.ts
- src/test/flutter_test_debug/debug/flutter_test.test.ts
- src/test/helpers.ts
Currently behind a preview flag.
Fixes #3147.
> Add support for VS Code's test runner

- snippets/dart.json
This could be subjective, but I think it's good to have a return type on every function. Every time I use the `main` snippet I find myself writing void anyway. You could also argue that I could make my own snippet, and that's true. But because dart is typed after all and `fun` uses void, why not?
> style: add return type of main

- package.json
Thought this would be a good way to familiarize myself with all the available settings. 
Also learned you can link to other settings with `#target.setting.id#`, and fixed two such instances.
Closes #3608
> Group settings by categories

- src/extension/analysis/file_tracker_das.ts
- src/extension/extension.ts
- src/extension/providers/dart_reference_provider.ts
Use that to navigate if available, otherwise fall back to requesting navigation directly from the analysis server.
> Subscribe to navigation events on open files

- src/debug/flutter_debug_impl.ts
- src/debug/flutter_run.ts
- src/debug/flutter_test_debug_impl.ts
- src/extension/commands/flutter.ts
- src/extension/flutter/flutter_daemon.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/debug/interfaces.ts
- src/shared/interfaces.ts
- src/shared/utils.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/flutter_snap/extension.test.ts
The goal here is to push some of this complex logic back into the editor and out of the debug adapter. The reason for this is that the debug adapters are moving to the SDK and will be reused by other editors so I'd like to keep the interface/args to them as simple/generic as possible.
@helin24 this refactors some of the Bazel work slightly, moving some things out of the adapters (in `./debug/`) into the configuration created by the client (`debug_config_provider`) - mostly removing the `workspaceConfig` that was previously passed through for some simpler (flat) fields in `args`.
- `wsConfig.skipTargetFlag` -> `omitTargetFlag`
- `wsConfig.flutterXxxScript` -> `customTool` + `customToolReplacesArgs`
- remove `wsConfig.flutterScript` (was unused) 
- remove `wsConfig. nonMainTargetPrefix` and …
> Remove workspaceConfig from DA, simplifying use of custom tools

- package.json
- src/extension/commands/open_in_other_editors.ts
Allows the `flutter.openInXcode` command on `macos` folders as well as `ios`.
Closes Dart-Code/Dart-Code#3817
> Add open in Xcode for macOS

- .github/workflows/build-and-test.yml
- .github/workflows/nightly-build.yml
- .github/workflows/stale.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/extension/extension.ts
- src/shared/vscode/device_manager.ts
- src/test/flutter/device_manager.test.ts
We aren't able to find project folders for workspaces with `forceFlutterWorkspace`, but we still want to request platforms from the daemon.
> Use empty folder path for bazel workspaces during device check

- package.json
- src/extension/sdk/utils.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/test_projects/bazel_workspace/flutter_hello_world_bazel/dart/config/ide/flutter.json
We want to avoid users needing to set their own SDK for bazel workspaces. Most users should be okay with the default SDK from our config file.
I was hoping to test that this default SDK doesn't override a user-set SDK, but there isn't currently an easy way to do this now. https://github.com/Dart-Code/Dart-Code/issues/4057
> Use a default Dart SDK for bazel projects

- src/extension/extension.ts
- src/extension/providers/debug_adapter_descriptor_factory.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/test_projects/bazel_workspace/flutter_hello_world_bazel/dart/config/ide/flutter.json
- src/test/test_projects/bazel_workspace/scripts/custom_tools.sh
This adds a generic tools script that we can use to call `debug_adapter`. I'm not sure if the tests pass because I was having trouble running the bazel tests locally, but I'll look at them a bit more to see if I can fix that.
> Use workspace tools script for debug

- src/extension/commands/debug.ts
- src/extension/flutter/vm_service_extensions.ts
- src/shared/utils/fs.ts
- src/shared/vscode/utils.ts
The current project folder finding method does not work for internal projects that don't use pubspec files, but we need to return these folders with their relative paths for DevTools root to be set correctly. I think we could eventually do this in DDS, but this may be the best option to have this in the next release (I'm not sure and would be open to doing something less hard coded).
> Translate folder paths for setting DevTools root

- package.json
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/sdk/utils.ts
- src/shared/utils/workspace.ts
- src/test/test_projects/bazel_workspace/flutter_hello_world_bazel/.vscode/settings.json
Is it okay to remove this option entirely? It looks like checking for Fuchsia workspaces is similar, so hopefully it's not too much work to always check for a bazel workspace.
> Remove preview bazel option

- src/extension/extension.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/shared/vscode/device_manager.ts
This is specifically for an internal project that requires users to start/restart a process on their local machine to expose devices.
> Show a prompt to reopen the workspace if devices aren't found

- src/extension/extension.ts
- src/extension/flutter/flutter_daemon.ts
We were previously always sending a daemon shutdown request, which would kill the shutdown process entirely if the daemon never started up.
This also shows the no devices message if the daemon doesn't start up for internal cases instead of the more generic daemon failed to start message.
> Fix daemon not ending / restarting on user request

- src/extension/extension.ts
- src/extension/providers/debug_config_provider.ts
- src/shared/vscode/device_manager.ts
I forgot to pass the port from the local device extension to debug config (oops!). Is there a better way to pass this through these functions?
> Pass automatic daemon port to debug config

- src/extension/providers/debug_config_provider.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/flutter_bazel/debug/flutter_run.test.ts
@helin24 does this solve the issue you had?
If there's a `program` we will try to infer a `cwd` from it, but if that fails, we should no longer use the workspace folder. We'll only use the workspace folder directly is there was no open file _or_ `program`.
Then, if we still don't have one (which we won't for a special `target` that doesn't have an enclosing `WorkspaceFolder`) we'll look for a common ancestor for all workspace folders.
> Don't infer cwd from workspace folder when there's an explicit program

- src/extension/flutter/flutter_daemon.ts
@DanTup `promptToReloadExtension` doesn't run activate again, so I'm not sure if there's something else I should use here to run the local device command again. Or perhaps I should move that logic into another area that is run again when `promptToReloadExtension` is called?
> Ping the daemon WIP

- src/extension/commands/debug.ts
- src/shared/interfaces.ts
- src/shared/utils/workspace.ts
- src/test/flutter_bazel/extension.test.ts
- src/test/test_projects/bazel_workspace/dart/config/ide/flutter.json
This is no longer needed since we only support running VS Code on a remote machine. (the original purpose was to make sure remote changes were synced on a local machine)
> Remove sync script

- package.json
- src/debug/dart_debug_impl.ts
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/providers/debug_adapter_hex_view_factory.ts
- src/extension/providers/debug_adapter_logger_factory.ts
- src/shared/capabilities/dart.ts
- src/shared/constants.ts
- src/shared/vscode/interfaces.ts
- src/test/dart_debug/debug/dart_cli.test.ts
- src/test/dart_debug_client.ts
- src/test/debug_helpers.ts
> Add support for toggling number format to hex

- package-lock.json
- package.json
- src/extension/analysis/analyzer_status_reporter.ts
- src/extension/analytics.ts
- src/extension/commands/debug.ts
- src/extension/extension.ts
Migrates all telemetry code to the new `TelemetrySender`/`TelemetryLogger` API.
> Use Telemetry v1.75 VSCode API

- src/extension/decorations/flutter_ui_guides_decorations.ts
Today I finally discovered that these flutter guides are a beta preview ! and so I enabled them and thought, why not having round corner? So this is the tiniest PR possible :) making only a simple change that makes these guides a little bit prettier hopefully...
> Round corner for flutter guides

- src/extension/sdk/dev_tools/embedded_view.ts
This is to overcome [a bug with VSCode that isn't allowing Devtools to use the copy api.](https://github.com/flutter/devtools/issues/5775)
I've added the allow permissions to the iframe so that if VSCode ever fixes this issue, we should be able to just start utilizing the original copy method right away :)
The complementary code from Devtools can be found in this PR: https://github.com/flutter/devtools/pull/6598
> Add listener for copy events above the devtools frame

- src/extension/api/dart_tooling_api.ts
- src/extension/api/interface.ts
- src/shared/vscode/device_manager.ts
+ add enablePlatformType method
See https://github.com/Dart-Code/Dart-Code/issues/4820
> Include unsupported devices sidebar in API device events

- package.json
- src/extension/config.ts
- src/shared/flutter/utils.ts
- src/test/flutter_debug/flutter_run.test.ts
We are changing the default for `--web-renderer` in the flutter tool ([issue](https://github.com/flutter/flutter/issues/149826)). This PR is doing the same thing in the VSCode extension.
**_Question to reviewers:_**
I prefer to not hardcode a default value here, and instead omit the `--web-renderer` argument by default. That way, we let the flutter tool decide what's the default. Is there a way to make the `dart.flutterWebRenderer` enum nullable?
> Add separate web renderer options for flutter-default and auto and set the default to flutter-default

- .github/workflows/build-and-test.yml
- src/extension/code_lens/flutter_dartpad_samples.ts
- src/extension/flutter/vm_service_extensions.ts
- src/shared/utils/outline_das.ts
- src/test/dart/commands/go_to_augmentations.test.ts
- src/test/dart_debug/dart_cli.test.ts
- src/test/dart_debug/dart_test.test.ts
- src/test/dart_debug_client.ts
- src/test/debug_client_ms.ts
- src/test/debug_helpers.ts
- src/test/flutter/providers/flutter_dartpad_samples_code_lens_provider.test.ts
- src/test/flutter_debug/flutter_run.test.ts
- src/test/flutter_test_debug/debug/flutter_test.test.ts
- src/test/helpers.ts
- src/test/web_debug/debug/web.test.ts
Fixes a number of issues with debugger tests, some related to the debug adapter now using URIs and some just differences in behaviour (such as always getting a stop-on-entry at the start before the debug adapter resumes).
Full test run that includes beta is here:
https://github.com/Dart-Code/Dart-Code/actions/runs/9779733837
> Fix debug integration tests for uris

- package.json
- src/extension/commands/packages.ts
- src/test/helpers.ts
- src/test/multi_root/commands.test.ts
- src/test/multi_root/extension.test.ts
This Pull Request adds a new command to the DartCode extension for Visual Studio Code, enabling users to `run pub get` for *all Dart projects* within the workspace. This feature streamlines the process of fetching dependencies for multiple projects, enhancing productivity and efficiency.
- Added a new command dart.getAllPubGet to execute pub get for all projects.
- Updated the command palette to include the new command.
- Modified the extension activation logic to register the new command.
> Feature: Add command to get packages from all projects

- package.json
This PR only fixes a typo and adds more consistency between all descriptions of legacy log options that allow an entry of `${name}` in log file paths.
> Fixing typo and consistency

- package.json
- src/extension/utils.ts
Adding the option to replace `~` for the home directory in paths that use backslashes.
Also, making clearer that only the noted substitutions are allowed and everything else will be left in the path as-is.
> Fix resolvePaths to handle Windows paths with backslashes

- src/extension/extension.ts
- src/extension/providers/debug_adapter_descriptor_factory.ts
- src/shared/capabilities/vscode.ts
This is a fix (workaround) for a potentially serious issue debugging Flutter on Windows with the incoming VS Code (editor) release. I plan to ship it a Dart-Code pre-release shortly (today) to get some testing and may ship in a stable release tomorrow or Thursday.
@andrewkolos @jwren @helin24 I would appreciate additional eyes over this change before the stable release if possible. It's not a particularly nice workaround but it's currently all I have.
A summary of the issue:
A recent breaking change in NodeJS means spawning a `.bat` shell script on Windows without explicitly setting `shell: true` will fail with an `EINVAL` error. The upcoming release of the VS Code editor (being prepared and likely to ship this or next week) updates to a version of NodeJS that includes that change. Our …
> Spawn Flutter debug adapter directly with dart.exe

- src/extension/extension.ts
- src/extension/user_prompts.ts
- src/shared/capabilities/dart.ts
- src/shared/constants.ts
- src/shared/vscode/user_prompts.ts
- src/shared/vscode/workspace.ts
- src/test/dart/user_prompts.test.ts
- src/test/helpers.ts
This adds two new fields to `DartCapabilities` for `isUnsupportedNow` and `isUnsupportedSoon` to determine whether to warn the user about unsupported SDKs. This is a necessary step before we can remove any legacy code (such as the legacy analysis server integration, or activating DevTools from pub!).
We always do the SDK check against the Dart SDK version, but if the current Dart SDK comes from Flutter, we will reference "Flutter" and its SDK version in the user-facing messages.
"Unsupported now" messages will always be shown as the intention is that the user will either upgrade their SDK or switch to an older extension.. this may seem annoying, but the extension will be broken in many ways when using an SDK that triggers this, so ignoring it is not an option - you must upgrade SDK or …
> Add the ability to show notifications when the current SDK is unsupported (or will be soon)

- package.json
- src/extension/config.ts
- src/extension/sdk/utils.ts
- src/shared/interfaces.ts
Fixes #5334 and #5117
Adds 2 configurations, "getDartSdkCommand" and "getFlutterSdkCommand".
Here are a few examples on how can it be used:
```json5
// Use the where option in mise
"dart.getFlutterSdkCommand": {
"executable": "mise",
"args": ["where", "flutter"],
}
// Custom script in the project
"dart.getFlutterSdkCommand": {
"executable": "tool/get_flutter_sdk.sh",
}
// Cross platform script in the project using Dart
"dart.getFlutterSdkCommand": {
"executable": "dart",
"args": ["tool/get_flutter_sdk.dart"],
}
// Bash command that concatenates the output of the Flutter SDK to get the Dart SDK
"dart.getDartSdkCommand": {
"executable": "bash",
"args": ["-c", "sdk=$(mise where flutter) || exit 1; echo \"$sdk/bin/cache/dart-sdk\""],
}
```
> Custom commands to obtain the Dart/Flutter SDK path 

- src/shared/constants.ts
Right now, when opening Android Studio from VSCode, the following is shown. The "Learn more" link goest to here: https://youtrack.jetbrains.com/articles/SUPPORT-A-56/How-to-handle-Switch-to-a-native-launcher-notification
> Prioritize using studio instead of studio.sh when opening Android Studio

- package.json
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/future_vs_code_api/mcp.d.ts
- src/extension/providers/mcp_server_definition_provider.ts
- src/shared/capabilities/dart.ts
- tsconfig.json
This uses the new VS Code API `registerMcpServerDefinitionProvider` to allow VS Code to ask us for MCP servers. If we're using a >= Dart 3.9.0-0 SDK and the (currently "hidden") `dart.experimentalMcpServer` setting is enabled, we will return the `dart mcp-server` command.
This allows VS Code to discover our MCP server and tools (which are then available to VS Code and other extensions).
Currently we don't provide a way to pass the DTD URI (at startup, or if we have to restart it, when the MCP server may continue to run - since VS Code controls its lifetime), but this will need adding.
@jakemac53 @kenzieschmoll
> [experimental] Add support for advertising the Dart SDK MCP server

- package.json
`build_runner` v2.5.0 changed the output format. The relevant new messages are:
Starting new build:
https://github.com/dart-lang/build/blob/8f9939f3c804edb91d4df33045536f6894472af0/build_runner_core/lib/src/logging/build_log.dart#L388-L390
Success/failure:
https://github.com/dart-lang/build/blob/8f9939f3c804edb91d4df33045536f6894472af0/build_runner_core/lib/src/logging/build_log.dart#L58-L62C41
The old background patterns are kept, since projects may keep using older versions of `build_runner` for a long while. I don't expect them to interfere with each other.
(As far as I can tell, there are no tests for problem matchers?)
Also: I didn't change the problem matchers, only the background ones. I don't think it's possible to build a single matcher that works with both old and new outputs, …
> Update background task patterns for build_runner 2.5.0

- src/shared/vscode/autolaunch.ts
- src/test/dart/debug/autolaunch.test.ts
If you include these fields in your `autolaunch.json`:
```js
"vmServiceUri": "ws://xxx",
"waitForVmServiceMs": 30000, // number of ms to wait for vmServiceUri to become accessible
```
Then we will wait up to `waitForVmServiceMs` for `vmServiceUri` to be connectable (as a WebSocket) before we start the debug session. If it never becomes available within this time, we will do nothing (we can add another flag later if we think we should have functionality to start the debug session anyway, but I suspect this won't be wanted, because stale files would result in failed debug sessions).
Fixes https://github.com/Dart-Code/Dart-Code/issues/5614
> Support waiting for a VM Service in AutoLaunch

- src/extension/extension.ts
- src/extension/flutter/flutter_project_watcher.ts
- src/shared/utils/cache.ts
- src/shared/vscode/utils.ts
If you start with a Dart-only workspace and later add a Flutter project, you'll now be prompted to reload:
Fixes https://github.com/Dart-Code/Dart-Code/issues/5612
> Prompt to reload when Flutter projects are added to a Dart-only workspace

- package.json
- src/extension/config.ts
- src/extension/extension.ts
- src/extension/providers/mcp_server_definition_provider.ts
- src/extension/views/packages_view.ts
- src/shared/capabilities/dart.ts
- src/shared/vscode/interfaces.ts
- src/test/dart/mcp_server.test.ts
Some of the built-in tools like `run_tests` overlap with built-in VS Code functionality, but the model might choose the SDK version despite having less functionality.
TODO
- `run_tests` seems like a like candidate
- `analyzer_files` - maybe? VS Code has Problems, but it's not clear if the model can read them all, or only for a given file?
- `create_project` ?
- `dart_fix` ?
- `hot_reload` ?
- `pub` - should we expose the built-in Dart-Code commands so it can call things that show in the UI?
**Edit:** For now, only excluding `runTests` because it's the only one that specifically does overlap- the others require us to expose new tools from Dart-Code, or VS Code changes (I've opened https://github.com/Dart-Code/Dart-Code/issues/5647 to track the problems tool replacing `analyze_files`).
> Add support for excluding MCP tools from the Dart MCP server

- syntaxes/dart.json.license
Noticed this typo as I was poking around.
> Update and rename dart.json.licence to dart.json.license
